L 10/18/2019 - 00:02:36: SourceMod error session started
L 10/18/2019 - 00:02:36: Info (map "c5m3_cemetery") (file "errors_20191018.log")
L 10/18/2019 - 00:02:36: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:02:36: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:02:36: [SM] Call stack trace:
L 10/18/2019 - 00:02:36: [SM]   [0] SetEntProp
L 10/18/2019 - 00:02:36: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:03:30: [SM] Exception reported: Client 6 is not in game
L 10/18/2019 - 00:03:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 00:03:30: [SM] Call stack trace:
L 10/18/2019 - 00:03:30: [SM]   [0] GetClientTeam
L 10/18/2019 - 00:03:30: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 00:03:31: Error log file session closed.
L 10/18/2019 - 00:19:06: SourceMod error session started
L 10/18/2019 - 00:19:06: Info (map "c5m4_quarter") (file "errors_20191018.log")
L 10/18/2019 - 00:19:06: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:19:06: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:19:06: [SM] Call stack trace:
L 10/18/2019 - 00:19:06: [SM]   [0] SetEntProp
L 10/18/2019 - 00:19:06: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:19:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:19:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:19:09: [SM] Call stack trace:
L 10/18/2019 - 00:19:09: [SM]   [0] SetEntProp
L 10/18/2019 - 00:19:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:19:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:19:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:19:11: [SM] Call stack trace:
L 10/18/2019 - 00:19:11: [SM]   [0] SetEntProp
L 10/18/2019 - 00:19:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:22:34: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 00:22:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 00:22:34: [SM] Call stack trace:
L 10/18/2019 - 00:22:34: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 00:22:34: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 00:22:34: [SM] Exception reported: Client 1 is not in game
L 10/18/2019 - 00:22:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 00:22:34: [SM] Call stack trace:
L 10/18/2019 - 00:22:34: [SM]   [0] GetClientTeam
L 10/18/2019 - 00:22:34: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 00:22:35: Error log file session closed.
L 10/18/2019 - 00:22:38: SourceMod error session started
L 10/18/2019 - 00:22:38: Info (map "c5m5_bridge") (file "errors_20191018.log")
L 10/18/2019 - 00:22:38: [SM] Exception reported: Client 5 is not in game
L 10/18/2019 - 00:22:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 00:22:38: [SM] Call stack trace:
L 10/18/2019 - 00:22:38: [SM]   [0] GetClientTeam
L 10/18/2019 - 00:22:38: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 00:24:44: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:24:44: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:24:44: [SM] Call stack trace:
L 10/18/2019 - 00:24:44: [SM]   [0] SetEntProp
L 10/18/2019 - 00:24:44: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:24:49: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:24:49: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:24:49: [SM] Call stack trace:
L 10/18/2019 - 00:24:49: [SM]   [0] SetEntProp
L 10/18/2019 - 00:24:49: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:31:38: [SM] Exception reported: Client 3 is not in game
L 10/18/2019 - 00:31:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 00:31:38: [SM] Call stack trace:
L 10/18/2019 - 00:31:38: [SM]   [0] GetClientTeam
L 10/18/2019 - 00:31:38: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 00:31:38: [SM] Exception reported: Entity 2 (2) is invalid
L 10/18/2019 - 00:31:38: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 00:31:38: [SM] Call stack trace:
L 10/18/2019 - 00:31:38: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 00:31:38: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 00:31:38: Error log file session closed.
L 10/18/2019 - 00:56:25: SourceMod error session started
L 10/18/2019 - 00:56:25: Info (map "c11m2_offices") (file "errors_20191018.log")
L 10/18/2019 - 00:56:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 00:56:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 00:56:25: [SM] Call stack trace:
L 10/18/2019 - 00:56:25: [SM]   [0] SetEntProp
L 10/18/2019 - 00:56:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 00:57:16: Error log file session closed.
L 10/18/2019 - 01:09:31: SourceMod error session started
L 10/18/2019 - 01:09:31: Info (map "c11m3_garage") (file "errors_20191018.log")
L 10/18/2019 - 01:09:31: [SM] Exception reported: Entity 9 (9) is invalid
L 10/18/2019 - 01:09:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 01:09:31: [SM] Call stack trace:
L 10/18/2019 - 01:09:31: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 01:09:31: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 01:09:32: Error log file session closed.
L 10/18/2019 - 01:11:03: SourceMod error session started
L 10/18/2019 - 01:11:03: Info (map "c11m4_terminal") (file "errors_20191018.log")
L 10/18/2019 - 01:11:03: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 01:11:03: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 01:11:03: [SM] Call stack trace:
L 10/18/2019 - 01:11:03: [SM]   [0] SetEntProp
L 10/18/2019 - 01:11:03: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 01:19:26: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 01:19:26: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 01:19:26: [SM] Call stack trace:
L 10/18/2019 - 01:19:26: [SM]   [0] SetEntProp
L 10/18/2019 - 01:19:26: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 01:20:05: [SM] Exception reported: Client 2 is not in game
L 10/18/2019 - 01:20:05: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 01:20:05: [SM] Call stack trace:
L 10/18/2019 - 01:20:05: [SM]   [0] GetClientTeam
L 10/18/2019 - 01:20:05: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 01:20:06: Error log file session closed.
L 10/18/2019 - 01:32:58: SourceMod error session started
L 10/18/2019 - 01:32:58: Info (map "c11m5_runway") (file "errors_20191018.log")
L 10/18/2019 - 01:32:58: [SM] Exception reported: Entity 4 (4) is invalid
L 10/18/2019 - 01:32:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 01:32:58: [SM] Call stack trace:
L 10/18/2019 - 01:32:58: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 01:32:58: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 01:35:09: Error log file session closed.
L 10/18/2019 - 01:47:41: SourceMod error session started
L 10/18/2019 - 01:47:41: Info (map "c10m1_caves") (file "errors_20191018.log")
L 10/18/2019 - 01:47:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 01:47:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 01:47:41: [SM] Call stack trace:
L 10/18/2019 - 01:47:41: [SM]   [0] SetEntProp
L 10/18/2019 - 01:47:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 01:48:07: Error log file session closed.
L 10/18/2019 - 01:50:43: SourceMod error session started
L 10/18/2019 - 01:50:43: Info (map "c10m2_drainage") (file "errors_20191018.log")
L 10/18/2019 - 01:50:43: [SM] Exception reported: Client index 490 is invalid
L 10/18/2019 - 01:50:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 01:50:43: [SM] Call stack trace:
L 10/18/2019 - 01:50:43: [SM]   [0] IsClientInGame
L 10/18/2019 - 01:50:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 01:50:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 01:50:49: [SM] Exception reported: Client index 490 is invalid
L 10/18/2019 - 01:50:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 01:50:49: [SM] Call stack trace:
L 10/18/2019 - 01:50:49: [SM]   [0] IsClientInGame
L 10/18/2019 - 01:50:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 01:50:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 01:50:55: [SM] Exception reported: Client index 490 is invalid
L 10/18/2019 - 01:50:55: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 01:50:55: [SM] Call stack trace:
L 10/18/2019 - 01:50:55: [SM]   [0] IsClientInGame
L 10/18/2019 - 01:50:55: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 01:50:55: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 01:51:05: [SM] Exception reported: Client index 490 is invalid
L 10/18/2019 - 01:51:05: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 01:51:05: [SM] Call stack trace:
L 10/18/2019 - 01:51:05: [SM]   [0] IsClientInGame
L 10/18/2019 - 01:51:05: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 01:51:05: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 01:54:30: [SM] Exception reported: Array index out-of-bounds (index 8, limit 8)
L 10/18/2019 - 01:54:30: [SM] Blaming: l4d2_antigodframer.smx
L 10/18/2019 - 01:54:30: [SM] Call stack trace:
L 10/18/2019 - 01:54:30: [SM]   [1] Line 76, C:\Users\Sir\Documents\NewScripting\l4d2_antigodframer.sp::CycCheck
L 10/18/2019 - 01:54:31: Error log file session closed.
L 10/18/2019 - 02:02:49: SourceMod error session started
L 10/18/2019 - 02:02:49: Info (map "c10m3_ranchhouse") (file "errors_20191018.log")
L 10/18/2019 - 02:02:49: [SM] Exception reported: Entity 6 (6) is invalid
L 10/18/2019 - 02:02:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 02:02:49: [SM] Call stack trace:
L 10/18/2019 - 02:02:49: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 02:02:49: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 02:04:57: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 02:04:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 02:04:57: [SM] Call stack trace:
L 10/18/2019 - 02:04:57: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 02:04:57: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 02:04:57: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 02:04:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 02:04:57: [SM] Call stack trace:
L 10/18/2019 - 02:04:57: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 02:04:57: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 02:05:06: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 02:05:06: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 02:05:06: [SM] Call stack trace:
L 10/18/2019 - 02:05:06: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 02:05:06: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 02:05:07: Error log file session closed.
L 10/18/2019 - 02:13:40: SourceMod error session started
L 10/18/2019 - 02:13:40: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 02:13:40: [CRASH] Accelerator uploaded crash dump: Crash ID: WT42-ZMKG-O7AV
L 10/18/2019 - 03:23:37: Error log file session closed.
L 10/18/2019 - 03:39:53: SourceMod error session started
L 10/18/2019 - 03:39:53: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 03:39:53: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 03:39:53: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 03:39:53: [SM] Call stack trace:
L 10/18/2019 - 03:39:53: [SM]   [0] SetEntProp
L 10/18/2019 - 03:39:53: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 03:40:32: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 03:40:32: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 03:40:32: [SM] Call stack trace:
L 10/18/2019 - 03:40:32: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 03:40:32: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 03:40:33: Error log file session closed.
L 10/18/2019 - 03:48:41: SourceMod error session started
L 10/18/2019 - 03:48:41: Info (map "c2m2_fairgrounds") (file "errors_20191018.log")
L 10/18/2019 - 03:48:41: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 03:48:41: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 03:48:41: [SM] Call stack trace:
L 10/18/2019 - 03:48:41: [SM]   [0] SetEntProp
L 10/18/2019 - 03:48:41: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 03:49:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 03:49:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 03:49:01: [SM] Call stack trace:
L 10/18/2019 - 03:49:01: [SM]   [0] SetEntProp
L 10/18/2019 - 03:49:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 03:56:03: [SM] Exception reported: Entity 4 (4) is invalid
L 10/18/2019 - 03:56:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 03:56:03: [SM] Call stack trace:
L 10/18/2019 - 03:56:03: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 03:56:03: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 03:56:03: Error log file session closed.
L 10/18/2019 - 03:59:16: SourceMod error session started
L 10/18/2019 - 03:59:16: Info (map "c2m3_coaster") (file "errors_20191018.log")
L 10/18/2019 - 03:59:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 03:59:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 03:59:16: [SM] Call stack trace:
L 10/18/2019 - 03:59:16: [SM]   [0] SetEntProp
L 10/18/2019 - 03:59:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 03:59:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 03:59:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 03:59:20: [SM] Call stack trace:
L 10/18/2019 - 03:59:20: [SM]   [0] SetEntProp
L 10/18/2019 - 03:59:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 04:02:40: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 04:02:40: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 04:02:40: [SM] Call stack trace:
L 10/18/2019 - 04:02:40: [SM]   [0] SetEntProp
L 10/18/2019 - 04:02:40: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 04:03:21: Error log file session closed.
L 10/18/2019 - 04:09:05: SourceMod error session started
L 10/18/2019 - 04:09:05: Info (map "c2m4_barns") (file "errors_20191018.log")
L 10/18/2019 - 04:09:05: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 04:09:05: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 04:09:05: [SM] Call stack trace:
L 10/18/2019 - 04:09:05: [SM]   [0] SetEntProp
L 10/18/2019 - 04:09:05: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 04:10:47: [SM] Exception reported: Client index 365 is invalid
L 10/18/2019 - 04:10:47: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 04:10:47: [SM] Call stack trace:
L 10/18/2019 - 04:10:47: [SM]   [0] IsClientInGame
L 10/18/2019 - 04:10:47: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 04:10:47: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 04:17:33: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 04:17:33: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:17:33: [SM] Call stack trace:
L 10/18/2019 - 04:17:33: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 04:17:33: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:17:34: Error log file session closed.
L 10/18/2019 - 04:17:40: SourceMod error session started
L 10/18/2019 - 04:17:40: Info (map "c10m1_caves") (file "errors_20191018.log")
L 10/18/2019 - 04:17:40: [SM] Exception reported: Client 8 is not in game
L 10/18/2019 - 04:17:40: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:17:40: [SM] Call stack trace:
L 10/18/2019 - 04:17:40: [SM]   [0] GetClientTeam
L 10/18/2019 - 04:17:40: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:17:46: [SM] Exception reported: Client 3 is not in game
L 10/18/2019 - 04:17:46: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:17:46: [SM] Call stack trace:
L 10/18/2019 - 04:17:46: [SM]   [0] GetClientTeam
L 10/18/2019 - 04:17:46: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:20:55: [SM] Exception reported: Client 7 is not in game
L 10/18/2019 - 04:20:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:20:55: [SM] Call stack trace:
L 10/18/2019 - 04:20:55: [SM]   [0] GetClientTeam
L 10/18/2019 - 04:20:55: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:30:40: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 04:30:40: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:30:40: [SM] Call stack trace:
L 10/18/2019 - 04:30:40: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 04:30:40: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:30:40: [SM] Exception reported: Entity 6 (6) is invalid
L 10/18/2019 - 04:30:40: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:30:40: [SM] Call stack trace:
L 10/18/2019 - 04:30:40: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 04:30:40: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:30:40: Error log file session closed.
L 10/18/2019 - 04:34:16: SourceMod error session started
L 10/18/2019 - 04:34:16: Info (map "c10m2_drainage") (file "errors_20191018.log")
L 10/18/2019 - 04:34:16: [SM] Exception reported: Client 8 is not in game
L 10/18/2019 - 04:34:16: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:34:16: [SM] Call stack trace:
L 10/18/2019 - 04:34:16: [SM]   [0] GetClientTeam
L 10/18/2019 - 04:34:16: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 04:35:00: [SM] Exception reported: Client 10 is not connected
L 10/18/2019 - 04:35:00: [SM] Blaming: l4d_tank_damage_announce.smx
L 10/18/2019 - 04:35:00: [SM] Call stack trace:
L 10/18/2019 - 04:35:00: [SM]   [0] GetClientName
L 10/18/2019 - 04:35:00: [SM]   [1] Line 242, C:\Users\Sir\Documents\NewNewScripting\l4d_tank_damage_announce.sp::PrintTankDamage
L 10/18/2019 - 04:35:00: [SM]   [2] Line 203, C:\Users\Sir\Documents\NewNewScripting\l4d_tank_damage_announce.sp::Timer_CheckTank
L 10/18/2019 - 04:35:09: [SM] Exception reported: Client 10 is not connected
L 10/18/2019 - 04:35:09: [SM] Blaming: l4d_tank_damage_announce.smx
L 10/18/2019 - 04:35:09: [SM] Call stack trace:
L 10/18/2019 - 04:35:09: [SM]   [0] GetClientName
L 10/18/2019 - 04:35:09: [SM]   [1] Line 242, C:\Users\Sir\Documents\NewNewScripting\l4d_tank_damage_announce.sp::PrintTankDamage
L 10/18/2019 - 04:35:09: [SM]   [2] Line 203, C:\Users\Sir\Documents\NewNewScripting\l4d_tank_damage_announce.sp::Timer_CheckTank
L 10/18/2019 - 04:35:56: [SM] Exception reported: Entity 8 (8) is invalid
L 10/18/2019 - 04:35:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 04:35:56: [SM] Call stack trace:
L 10/18/2019 - 04:35:56: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 04:35:56: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 04:39:33: Error log file session closed.
L 10/18/2019 - 04:43:07: SourceMod error session started
L 10/18/2019 - 04:43:07: Info (map "c10m3_ranchhouse") (file "errors_20191018.log")
L 10/18/2019 - 04:43:07: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 04:43:07: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 04:43:07: [SM] Call stack trace:
L 10/18/2019 - 04:43:07: [SM]   [0] SetEntProp
L 10/18/2019 - 04:43:07: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 04:51:04: Error log file session closed.
L 10/18/2019 - 05:04:17: SourceMod error session started
L 10/18/2019 - 05:04:17: Info (map "c10m4_mainstreet") (file "errors_20191018.log")
L 10/18/2019 - 05:04:17: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 05:04:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 05:04:17: [SM] Call stack trace:
L 10/18/2019 - 05:04:17: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 05:04:17: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 05:04:18: Error log file session closed.
L 10/18/2019 - 05:11:06: SourceMod error session started
L 10/18/2019 - 05:11:06: Info (map "c10m5_houseboat") (file "errors_20191018.log")
L 10/18/2019 - 05:11:06: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 05:11:06: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 05:11:06: [SM] Call stack trace:
L 10/18/2019 - 05:11:06: [SM]   [0] SetEntProp
L 10/18/2019 - 05:11:06: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 05:13:13: [SM] Exception reported: Client index 335 is invalid
L 10/18/2019 - 05:13:13: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 05:13:13: [SM] Call stack trace:
L 10/18/2019 - 05:13:13: [SM]   [0] IsClientInGame
L 10/18/2019 - 05:13:13: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 05:13:13: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 05:17:53: Error log file session closed.
L 10/18/2019 - 05:18:29: SourceMod error session started
L 10/18/2019 - 05:18:29: Info (map "c7m1_docks") (file "errors_20191018.log")
L 10/18/2019 - 05:18:29: [SM] Exception reported: Client 3 is not in game
L 10/18/2019 - 05:18:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 05:18:29: [SM] Call stack trace:
L 10/18/2019 - 05:18:29: [SM]   [0] GetClientTeam
L 10/18/2019 - 05:18:29: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 05:18:48: SourceMod error session started
L 10/18/2019 - 05:18:48: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 05:18:48: [CRASH] Accelerator uploaded crash dump: Crash ID: TOAS-TJJQ-FPDH
L 10/18/2019 - 12:48:33: Error log file session closed.
L 10/18/2019 - 13:00:31: SourceMod error session started
L 10/18/2019 - 13:00:31: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 13:00:31: [SM] Exception reported: Client 2 is not in game
L 10/18/2019 - 13:00:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:00:31: [SM] Call stack trace:
L 10/18/2019 - 13:00:31: [SM]   [0] GetClientTeam
L 10/18/2019 - 13:00:31: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 13:04:11: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 13:04:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:04:11: [SM] Call stack trace:
L 10/18/2019 - 13:04:11: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:04:11: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 13:06:10: [SM] Exception reported: Client index 396 is invalid
L 10/18/2019 - 13:06:10: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 13:06:10: [SM] Call stack trace:
L 10/18/2019 - 13:06:10: [SM]   [0] IsClientInGame
L 10/18/2019 - 13:06:10: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 13:06:10: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 13:07:28: [SM] Exception reported: Entity 9 (9) is invalid
L 10/18/2019 - 13:07:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:07:28: [SM] Call stack trace:
L 10/18/2019 - 13:07:28: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:07:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 13:07:28: Error log file session closed.
L 10/18/2019 - 13:14:11: SourceMod error session started
L 10/18/2019 - 13:14:11: Info (map "c2m2_fairgrounds") (file "errors_20191018.log")
L 10/18/2019 - 13:14:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 13:14:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 13:14:11: [SM] Call stack trace:
L 10/18/2019 - 13:14:11: [SM]   [0] SetEntProp
L 10/18/2019 - 13:14:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 13:14:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 13:14:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 13:14:11: [SM] Call stack trace:
L 10/18/2019 - 13:14:11: [SM]   [0] SetEntProp
L 10/18/2019 - 13:14:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 13:20:57: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 13:20:57: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:20:57: [SM] Call stack trace:
L 10/18/2019 - 13:20:57: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:20:57: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 13:21:18: [SM] Exception reported: Entity 5 (5) is invalid
L 10/18/2019 - 13:21:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:21:18: [SM] Call stack trace:
L 10/18/2019 - 13:21:18: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:21:18: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 13:21:18: Error log file session closed.
L 10/18/2019 - 13:25:28: SourceMod error session started
L 10/18/2019 - 13:25:28: Info (map "c2m3_coaster") (file "errors_20191018.log")
L 10/18/2019 - 13:25:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 13:25:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 13:25:28: [SM] Call stack trace:
L 10/18/2019 - 13:25:28: [SM]   [0] SetEntProp
L 10/18/2019 - 13:25:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 13:25:33: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 13:25:33: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 13:25:33: [SM] Call stack trace:
L 10/18/2019 - 13:25:33: [SM]   [0] SetEntProp
L 10/18/2019 - 13:25:33: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 13:29:00: [SM] Exception reported: Entity 2 (2) is invalid
L 10/18/2019 - 13:29:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:29:00: [SM] Call stack trace:
L 10/18/2019 - 13:29:00: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:29:00: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 13:29:00: [SM] Exception reported: Client 6 is not in game
L 10/18/2019 - 13:29:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:29:00: [SM] Call stack trace:
L 10/18/2019 - 13:29:00: [SM]   [0] GetClientTeam
L 10/18/2019 - 13:29:00: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 13:31:17: [SM] Exception reported: Client index 252 is invalid
L 10/18/2019 - 13:31:17: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 13:31:17: [SM] Call stack trace:
L 10/18/2019 - 13:31:17: [SM]   [0] IsClientInGame
L 10/18/2019 - 13:31:17: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 13:31:17: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 13:31:21: [SM] Exception reported: Client index 252 is invalid
L 10/18/2019 - 13:31:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 13:31:21: [SM] Call stack trace:
L 10/18/2019 - 13:31:21: [SM]   [0] IsClientInGame
L 10/18/2019 - 13:31:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 13:31:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 13:31:31: [SM] Exception reported: Client index 252 is invalid
L 10/18/2019 - 13:31:31: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 13:31:31: [SM] Call stack trace:
L 10/18/2019 - 13:31:31: [SM]   [0] IsClientInGame
L 10/18/2019 - 13:31:31: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 13:31:31: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 13:32:39: Error log file session closed.
L 10/18/2019 - 13:37:11: SourceMod error session started
L 10/18/2019 - 13:37:11: Info (map "c2m4_barns") (file "errors_20191018.log")
L 10/18/2019 - 13:37:11: [SM] Exception reported: Entity 7 (7) is invalid
L 10/18/2019 - 13:37:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:37:11: [SM] Call stack trace:
L 10/18/2019 - 13:37:11: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:37:11: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 13:41:58: Error log file session closed.
L 10/18/2019 - 13:46:41: SourceMod error session started
L 10/18/2019 - 13:46:41: Info (map "c2m5_concert") (file "errors_20191018.log")
L 10/18/2019 - 13:46:41: [SM] Exception reported: Entity 2 (2) is invalid
L 10/18/2019 - 13:46:41: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 13:46:41: [SM] Call stack trace:
L 10/18/2019 - 13:46:41: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 13:46:41: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 13:46:43: Error log file session closed.
L 10/18/2019 - 13:55:19: SourceMod error session started
L 10/18/2019 - 13:55:19: Info (map "c3m1_plankcountry") (file "errors_20191018.log")
L 10/18/2019 - 13:55:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 13:55:19: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 13:55:19: [SM] Call stack trace:
L 10/18/2019 - 13:55:19: [SM]   [0] SetEntProp
L 10/18/2019 - 13:55:19: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 13:58:28: Error log file session closed.
L 10/18/2019 - 14:03:35: SourceMod error session started
L 10/18/2019 - 14:03:35: Info (map "c3m2_swamp") (file "errors_20191018.log")
L 10/18/2019 - 14:03:35: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/18/2019 - 14:03:35: [SM] Blaming: l4d2_playstats.smx
L 10/18/2019 - 14:03:35: [SM] Call stack trace:
L 10/18/2019 - 14:03:35: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/18/2019 - 14:03:35: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/18/2019 - 14:03:35: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/18/2019 - 14:03:35: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/18/2019 - 14:03:50: [SM] Exception reported: Entity 7 (7) is invalid
L 10/18/2019 - 14:03:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 14:03:50: [SM] Call stack trace:
L 10/18/2019 - 14:03:50: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 14:03:50: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 14:05:33: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 14:05:33: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 14:05:33: [SM] Call stack trace:
L 10/18/2019 - 14:05:33: [SM]   [0] SetEntProp
L 10/18/2019 - 14:05:33: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 14:05:40: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 14:05:40: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 14:05:40: [SM] Call stack trace:
L 10/18/2019 - 14:05:40: [SM]   [0] SetEntProp
L 10/18/2019 - 14:05:40: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 14:06:45: Error log file session closed.
L 10/18/2019 - 14:09:55: SourceMod error session started
L 10/18/2019 - 14:09:55: Info (map "c3m3_shantytown") (file "errors_20191018.log")
L 10/18/2019 - 14:09:55: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 14:09:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 14:09:55: [SM] Call stack trace:
L 10/18/2019 - 14:09:55: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 14:09:55: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 14:09:55: [SM] Exception reported: Entity 10 (10) is invalid
L 10/18/2019 - 14:09:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 14:09:55: [SM] Call stack trace:
L 10/18/2019 - 14:09:55: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 14:09:55: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 14:11:43: SourceMod error session started
L 10/18/2019 - 14:11:43: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 14:11:43: [CRASH] Accelerator uploaded crash dump: Crash ID: WQ5K-EJZ6-UAHL
L 10/18/2019 - 14:16:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 14:16:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 14:16:12: [SM] Call stack trace:
L 10/18/2019 - 14:16:12: [SM]   [0] SetEntProp
L 10/18/2019 - 14:16:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 14:54:37: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 14:54:37: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 14:54:37: [SM] Call stack trace:
L 10/18/2019 - 14:54:37: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 14:54:37: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 14:54:37: Error log file session closed.
L 10/18/2019 - 14:56:23: SourceMod error session started
L 10/18/2019 - 14:56:23: Info (map "c10m1_caves") (file "errors_20191018.log")
L 10/18/2019 - 14:56:23: [SM] Exception reported: Client 6 is not in game
L 10/18/2019 - 14:56:23: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 14:56:23: [SM] Call stack trace:
L 10/18/2019 - 14:56:23: [SM]   [0] GetClientTeam
L 10/18/2019 - 14:56:23: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 14:56:23: Error log file session closed.
L 10/18/2019 - 14:58:05: SourceMod error session started
L 10/18/2019 - 14:58:05: Info (map "c10m1_caves") (file "errors_20191018.log")
L 10/18/2019 - 14:58:05: [SM] Exception reported: Client 6 is not in game
L 10/18/2019 - 14:58:05: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 14:58:05: [SM] Call stack trace:
L 10/18/2019 - 14:58:05: [SM]   [0] GetClientTeam
L 10/18/2019 - 14:58:05: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:01:54: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:01:54: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:01:54: [SM] Call stack trace:
L 10/18/2019 - 15:01:54: [SM]   [0] SetEntProp
L 10/18/2019 - 15:01:54: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:06:30: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:06:30: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:06:30: [SM] Call stack trace:
L 10/18/2019 - 15:06:30: [SM]   [0] SetEntProp
L 10/18/2019 - 15:06:30: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:06:53: Error log file session closed.
L 10/18/2019 - 15:08:55: SourceMod error session started
L 10/18/2019 - 15:08:55: Info (map "c10m2_drainage") (file "errors_20191018.log")
L 10/18/2019 - 15:08:55: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:08:55: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:08:55: [SM] Call stack trace:
L 10/18/2019 - 15:08:55: [SM]   [0] SetEntProp
L 10/18/2019 - 15:08:55: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:09:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:09:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:09:09: [SM] Call stack trace:
L 10/18/2019 - 15:09:09: [SM]   [0] SetEntProp
L 10/18/2019 - 15:09:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:13:17: [SM] Exception reported: Entity 8 (8) is invalid
L 10/18/2019 - 15:13:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:13:17: [SM] Call stack trace:
L 10/18/2019 - 15:13:17: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:13:17: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 15:15:27: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:15:27: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:15:27: [SM] Call stack trace:
L 10/18/2019 - 15:15:27: [SM]   [0] SetEntProp
L 10/18/2019 - 15:15:27: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:15:30: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:15:30: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:15:30: [SM] Call stack trace:
L 10/18/2019 - 15:15:30: [SM]   [0] SetEntProp
L 10/18/2019 - 15:15:30: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:19:17: [SM] Exception reported: Entity 4 (4) is invalid
L 10/18/2019 - 15:19:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:19:17: [SM] Call stack trace:
L 10/18/2019 - 15:19:17: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:19:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:19:17: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 15:19:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:19:17: [SM] Call stack trace:
L 10/18/2019 - 15:19:17: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:19:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:19:18: Error log file session closed.
L 10/18/2019 - 15:22:12: SourceMod error session started
L 10/18/2019 - 15:22:12: Info (map "c10m3_ranchhouse") (file "errors_20191018.log")
L 10/18/2019 - 15:22:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:22:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:22:12: [SM] Call stack trace:
L 10/18/2019 - 15:22:12: [SM]   [0] SetEntProp
L 10/18/2019 - 15:22:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:22:19: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 15:22:19: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 15:22:19: [SM] Call stack trace:
L 10/18/2019 - 15:22:19: [SM]   [0] SetEntProp
L 10/18/2019 - 15:22:19: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 15:26:48: [SM] Exception reported: Entity 11 (11) is invalid
L 10/18/2019 - 15:26:48: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:26:48: [SM] Call stack trace:
L 10/18/2019 - 15:26:48: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:26:48: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 15:26:48: [SM] Exception reported: Client 8 is not in game
L 10/18/2019 - 15:26:48: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:26:48: [SM] Call stack trace:
L 10/18/2019 - 15:26:48: [SM]   [0] GetClientTeam
L 10/18/2019 - 15:26:48: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:26:49: Error log file session closed.
L 10/18/2019 - 15:45:58: SourceMod error session started
L 10/18/2019 - 15:45:58: Info (map "c10m5_houseboat") (file "errors_20191018.log")
L 10/18/2019 - 15:45:58: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 15:45:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:45:58: [SM] Call stack trace:
L 10/18/2019 - 15:45:58: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:45:58: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:45:58: [SM] Exception reported: Entity 3 (3) is invalid
L 10/18/2019 - 15:45:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:45:58: [SM] Call stack trace:
L 10/18/2019 - 15:45:58: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:45:58: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:45:59: Error log file session closed.
L 10/18/2019 - 15:47:57: SourceMod error session started
L 10/18/2019 - 15:47:57: Info (map "c13m1_alpinecreek") (file "errors_20191018.log")
L 10/18/2019 - 15:47:57: [SM] Exception reported: Client index 395 is invalid
L 10/18/2019 - 15:47:57: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 15:47:57: [SM] Call stack trace:
L 10/18/2019 - 15:47:57: [SM]   [0] IsClientInGame
L 10/18/2019 - 15:47:57: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 15:47:57: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 15:47:57: [SM] Exception reported: Client index 395 is invalid
L 10/18/2019 - 15:47:57: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 15:47:57: [SM] Call stack trace:
L 10/18/2019 - 15:47:57: [SM]   [0] IsClientInGame
L 10/18/2019 - 15:47:57: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 15:47:57: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 15:49:14: [SM] Exception reported: Client 6 is not in game
L 10/18/2019 - 15:49:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:49:14: [SM] Call stack trace:
L 10/18/2019 - 15:49:14: [SM]   [0] GetClientTeam
L 10/18/2019 - 15:49:14: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:52:30: [SM] Exception reported: Client index 408 is invalid
L 10/18/2019 - 15:52:30: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 15:52:30: [SM] Call stack trace:
L 10/18/2019 - 15:52:30: [SM]   [0] IsClientInGame
L 10/18/2019 - 15:52:30: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 15:52:30: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 15:53:25: Error log file session closed.
L 10/18/2019 - 15:55:28: SourceMod error session started
L 10/18/2019 - 15:55:28: Info (map "c13m2_southpinestream") (file "errors_20191018.log")
L 10/18/2019 - 15:55:28: [SM] Exception reported: Client 9 is not in game
L 10/18/2019 - 15:55:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:55:28: [SM] Call stack trace:
L 10/18/2019 - 15:55:28: [SM]   [0] GetClientTeam
L 10/18/2019 - 15:55:28: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 15:56:28: [SM] Exception reported: Entity 5 (5) is invalid
L 10/18/2019 - 15:56:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 15:56:28: [SM] Call stack trace:
L 10/18/2019 - 15:56:28: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 15:56:28: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 15:57:54: SourceMod error session started
L 10/18/2019 - 15:57:54: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 15:57:54: [CRASH] Accelerator uploaded crash dump: Crash ID: T45C-T3GG-OTDE
L 10/18/2019 - 18:09:10: [SM] Exception reported: Client 1 is not in game
L 10/18/2019 - 18:09:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 18:09:10: [SM] Call stack trace:
L 10/18/2019 - 18:09:10: [SM]   [0] GetClientTeam
L 10/18/2019 - 18:09:10: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 19:52:26: Error log file session closed.
L 10/18/2019 - 19:59:20: SourceMod error session started
L 10/18/2019 - 19:59:20: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 19:59:20: [SM] Exception reported: Client index 284 is invalid
L 10/18/2019 - 19:59:20: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 19:59:20: [SM] Call stack trace:
L 10/18/2019 - 19:59:20: [SM]   [0] IsClientInGame
L 10/18/2019 - 19:59:20: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 19:59:20: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 20:04:28: [SM] Exception reported: Entity 5 (5) is invalid
L 10/18/2019 - 20:04:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:04:28: [SM] Call stack trace:
L 10/18/2019 - 20:04:28: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:04:28: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:04:28: [SM] Exception reported: Entity 2 (2) is invalid
L 10/18/2019 - 20:04:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:04:28: [SM] Call stack trace:
L 10/18/2019 - 20:04:28: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:04:28: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:04:28: [SM] Exception reported: Client 5 is not in game
L 10/18/2019 - 20:04:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:04:28: [SM] Call stack trace:
L 10/18/2019 - 20:04:28: [SM]   [0] GetClientTeam
L 10/18/2019 - 20:04:28: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:04:29: Error log file session closed.
L 10/18/2019 - 20:09:08: SourceMod error session started
L 10/18/2019 - 20:09:08: Info (map "c2m2_fairgrounds") (file "errors_20191018.log")
L 10/18/2019 - 20:09:08: [SM] Exception reported: Client index 286 is invalid
L 10/18/2019 - 20:09:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 20:09:08: [SM] Call stack trace:
L 10/18/2019 - 20:09:08: [SM]   [0] IsClientInGame
L 10/18/2019 - 20:09:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 20:09:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 20:09:08: [SM] Exception reported: Client index 286 is invalid
L 10/18/2019 - 20:09:08: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 20:09:08: [SM] Call stack trace:
L 10/18/2019 - 20:09:08: [SM]   [0] IsClientInGame
L 10/18/2019 - 20:09:08: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 20:09:08: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 20:11:18: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 20:11:18: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 20:11:18: [SM] Call stack trace:
L 10/18/2019 - 20:11:18: [SM]   [0] SetEntProp
L 10/18/2019 - 20:11:18: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 20:18:50: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 20:18:50: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 20:18:50: [SM] Call stack trace:
L 10/18/2019 - 20:18:50: [SM]   [0] SetEntProp
L 10/18/2019 - 20:18:50: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 20:20:48: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 20:20:48: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 20:20:48: [SM] Call stack trace:
L 10/18/2019 - 20:20:48: [SM]   [0] SetEntProp
L 10/18/2019 - 20:20:48: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 20:21:17: [SM] Exception reported: Entity 1 (1) is invalid
L 10/18/2019 - 20:21:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:21:17: [SM] Call stack trace:
L 10/18/2019 - 20:21:17: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:21:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:21:17: [SM] Exception reported: Entity 3 (3) is invalid
L 10/18/2019 - 20:21:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:21:17: [SM] Call stack trace:
L 10/18/2019 - 20:21:17: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:21:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:21:17: Error log file session closed.
L 10/18/2019 - 20:24:05: SourceMod error session started
L 10/18/2019 - 20:24:05: Info (map "c2m3_coaster") (file "errors_20191018.log")
L 10/18/2019 - 20:24:05: [SM] Exception reported: Client index 339 is invalid
L 10/18/2019 - 20:24:05: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 20:24:05: [SM] Call stack trace:
L 10/18/2019 - 20:24:05: [SM]   [0] IsClientInGame
L 10/18/2019 - 20:24:05: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 20:24:05: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 20:24:09: [SM] Exception reported: Client index 339 is invalid
L 10/18/2019 - 20:24:09: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/18/2019 - 20:24:09: [SM] Call stack trace:
L 10/18/2019 - 20:24:09: [SM]   [0] IsClientInGame
L 10/18/2019 - 20:24:09: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/18/2019 - 20:24:09: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/18/2019 - 20:27:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/18/2019 - 20:27:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/18/2019 - 20:27:57: [SM] Call stack trace:
L 10/18/2019 - 20:27:57: [SM]   [0] SetEntProp
L 10/18/2019 - 20:27:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/18/2019 - 20:36:34: [SM] Exception reported: Client 9 is not in game
L 10/18/2019 - 20:36:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:36:34: [SM] Call stack trace:
L 10/18/2019 - 20:36:34: [SM]   [0] GetClientTeam
L 10/18/2019 - 20:36:34: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:37:55: Error log file session closed.
L 10/18/2019 - 20:56:01: SourceMod error session started
L 10/18/2019 - 20:56:01: Info (map "c2m4_barns") (file "errors_20191018.log")
L 10/18/2019 - 20:56:01: [SM] Exception reported: Entity 7 (7) is invalid
L 10/18/2019 - 20:56:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:56:01: [SM] Call stack trace:
L 10/18/2019 - 20:56:01: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:56:01: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:56:01: [SM] Exception reported: Entity 7 (7) is invalid
L 10/18/2019 - 20:56:01: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:56:01: [SM] Call stack trace:
L 10/18/2019 - 20:56:01: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:56:01: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/18/2019 - 20:56:18: [SM] Exception reported: Entity 6 (6) is invalid
L 10/18/2019 - 20:56:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/18/2019 - 20:56:18: [SM] Call stack trace:
L 10/18/2019 - 20:56:18: [SM]   [0] GetEntDataEnt2
L 10/18/2019 - 20:56:18: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/18/2019 - 20:57:24: SourceMod error session started
L 10/18/2019 - 20:57:24: Info (map "c2m1_highway") (file "errors_20191018.log")
L 10/18/2019 - 20:57:24: [CRASH] Accelerator uploaded crash dump: Crash ID: UHP4-VSAZ-LXJE
