L 10/16/2019 - 00:03:02: SourceMod error session started
L 10/16/2019 - 00:03:02: Info (map "c8m3_sewers") (file "errors_20191016.log")
L 10/16/2019 - 00:03:02: [SM] Exception reported: Client 6 is not in game
L 10/16/2019 - 00:03:02: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:03:02: [SM] Call stack trace:
L 10/16/2019 - 00:03:02: [SM]   [0] GetClientTeam
L 10/16/2019 - 00:03:02: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:03:03: Error log file session closed.
L 10/16/2019 - 00:09:34: SourceMod error session started
L 10/16/2019 - 00:09:34: Info (map "c8m4_interior") (file "errors_20191016.log")
L 10/16/2019 - 00:09:34: [SM] Exception reported: Entity 4 (4) is invalid
L 10/16/2019 - 00:09:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:09:34: [SM] Call stack trace:
L 10/16/2019 - 00:09:34: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 00:09:34: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 00:10:59: [SM] Exception reported: Client index 229 is invalid
L 10/16/2019 - 00:10:59: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 00:10:59: [SM] Call stack trace:
L 10/16/2019 - 00:10:59: [SM]   [0] IsClientInGame
L 10/16/2019 - 00:10:59: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 00:10:59: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 00:14:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 00:14:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 00:14:12: [SM] Call stack trace:
L 10/16/2019 - 00:14:12: [SM]   [0] SetEntProp
L 10/16/2019 - 00:14:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 00:14:16: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 00:14:16: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 00:14:16: [SM] Call stack trace:
L 10/16/2019 - 00:14:16: [SM]   [0] SetEntProp
L 10/16/2019 - 00:14:16: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 00:14:57: Error log file session closed.
L 10/16/2019 - 00:17:39: SourceMod error session started
L 10/16/2019 - 00:17:39: Info (map "c8m5_rooftop") (file "errors_20191016.log")
L 10/16/2019 - 00:17:39: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 00:17:39: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 00:17:39: [SM] Call stack trace:
L 10/16/2019 - 00:17:39: [SM]   [0] SetEntProp
L 10/16/2019 - 00:17:39: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 00:28:11: [SM] Exception reported: Client index 263 is invalid
L 10/16/2019 - 00:28:11: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 00:28:11: [SM] Call stack trace:
L 10/16/2019 - 00:28:11: [SM]   [0] IsClientInGame
L 10/16/2019 - 00:28:11: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 00:28:11: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 00:28:15: [SM] Exception reported: Client index 263 is invalid
L 10/16/2019 - 00:28:15: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 00:28:15: [SM] Call stack trace:
L 10/16/2019 - 00:28:15: [SM]   [0] IsClientInGame
L 10/16/2019 - 00:28:15: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 00:28:15: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 00:28:16: [SM] Exception reported: Client index 263 is invalid
L 10/16/2019 - 00:28:16: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 00:28:16: [SM] Call stack trace:
L 10/16/2019 - 00:28:16: [SM]   [0] IsClientInGame
L 10/16/2019 - 00:28:16: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 00:28:16: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 00:30:10: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 00:30:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:30:10: [SM] Call stack trace:
L 10/16/2019 - 00:30:10: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 00:30:10: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:30:10: [SM] Exception reported: Entity 9 (9) is invalid
L 10/16/2019 - 00:30:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:30:10: [SM] Call stack trace:
L 10/16/2019 - 00:30:10: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 00:30:10: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:30:20: [SM] Exception reported: Client 2 is not in game
L 10/16/2019 - 00:30:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:30:20: [SM] Call stack trace:
L 10/16/2019 - 00:30:20: [SM]   [0] GetClientTeam
L 10/16/2019 - 00:30:20: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:30:20: Error log file session closed.
L 10/16/2019 - 00:30:33: SourceMod error session started
L 10/16/2019 - 00:30:33: Info (map "c12m1_hilltop") (file "errors_20191016.log")
L 10/16/2019 - 00:30:33: [SM] Exception reported: Client 1 is not in game
L 10/16/2019 - 00:30:33: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:30:33: [SM] Call stack trace:
L 10/16/2019 - 00:30:33: [SM]   [0] GetClientTeam
L 10/16/2019 - 00:30:33: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:31:34: SourceMod error session started
L 10/16/2019 - 00:31:34: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 00:31:34: [CRASH] Accelerator uploaded crash dump: Crash ID: JHRC-TI2J-VL2E
L 10/16/2019 - 00:46:44: Error log file session closed.
L 10/16/2019 - 00:50:14: SourceMod error session started
L 10/16/2019 - 00:50:14: Info (map "c10m1_caves") (file "errors_20191016.log")
L 10/16/2019 - 00:50:14: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 00:50:14: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:50:14: [SM] Call stack trace:
L 10/16/2019 - 00:50:14: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 00:50:14: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:50:14: Error log file session closed.
L 10/16/2019 - 00:59:58: SourceMod error session started
L 10/16/2019 - 00:59:58: Info (map "c10m1_caves") (file "errors_20191016.log")
L 10/16/2019 - 00:59:58: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 00:59:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 00:59:58: [SM] Call stack trace:
L 10/16/2019 - 00:59:58: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 00:59:58: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 00:59:58: Error log file session closed.
L 10/16/2019 - 01:22:35: SourceMod error session started
L 10/16/2019 - 01:22:35: Info (map "c10m3_ranchhouse") (file "errors_20191016.log")
L 10/16/2019 - 01:22:35: [SM] Exception reported: Client index 87 is invalid
L 10/16/2019 - 01:22:35: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 01:22:35: [SM] Call stack trace:
L 10/16/2019 - 01:22:35: [SM]   [0] IsClientInGame
L 10/16/2019 - 01:22:35: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 01:22:35: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 01:24:57: Error log file session closed.
L 10/16/2019 - 01:38:26: SourceMod error session started
L 10/16/2019 - 01:38:26: Info (map "c10m5_houseboat") (file "errors_20191016.log")
L 10/16/2019 - 01:38:26: [SM] Exception reported: Entity 4 (4) is invalid
L 10/16/2019 - 01:38:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 01:38:26: [SM] Call stack trace:
L 10/16/2019 - 01:38:26: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 01:38:26: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 01:42:29: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 01:42:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 01:42:29: [SM] Call stack trace:
L 10/16/2019 - 01:42:29: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 01:42:29: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 01:42:30: Error log file session closed.
L 10/16/2019 - 01:42:34: SourceMod error session started
L 10/16/2019 - 01:42:34: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 01:42:34: [SM] Exception reported: Client 3 is not in game
L 10/16/2019 - 01:42:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 01:42:34: [SM] Call stack trace:
L 10/16/2019 - 01:42:34: [SM]   [0] GetClientTeam
L 10/16/2019 - 01:42:34: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 01:42:35: [SM] Exception reported: Client 6 is not in game
L 10/16/2019 - 01:42:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 01:42:35: [SM] Call stack trace:
L 10/16/2019 - 01:42:35: [SM]   [0] GetClientTeam
L 10/16/2019 - 01:42:35: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 01:54:44: [SM] Exception reported: Client 5 is not in game
L 10/16/2019 - 01:54:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 01:54:44: [SM] Call stack trace:
L 10/16/2019 - 01:54:44: [SM]   [0] GetClientTeam
L 10/16/2019 - 01:54:44: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 01:54:45: Error log file session closed.
L 10/16/2019 - 02:05:10: SourceMod error session started
L 10/16/2019 - 02:05:10: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 02:05:10: [SM] Exception reported: Entity 8 (8) is invalid
L 10/16/2019 - 02:05:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:05:10: [SM] Call stack trace:
L 10/16/2019 - 02:05:10: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 02:05:10: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:10:08: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 02:10:08: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 02:10:08: [SM] Call stack trace:
L 10/16/2019 - 02:10:08: [SM]   [0] SetEntProp
L 10/16/2019 - 02:10:08: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 02:11:03: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 02:11:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:11:03: [SM] Call stack trace:
L 10/16/2019 - 02:11:03: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 02:11:03: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:11:03: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 02:11:03: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:11:03: [SM] Call stack trace:
L 10/16/2019 - 02:11:03: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 02:11:03: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:11:04: Error log file session closed.
L 10/16/2019 - 02:14:24: SourceMod error session started
L 10/16/2019 - 02:14:24: Info (map "c2m2_fairgrounds") (file "errors_20191016.log")
L 10/16/2019 - 02:14:24: [SM] Exception reported: Client index 309 is invalid
L 10/16/2019 - 02:14:24: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 02:14:24: [SM] Call stack trace:
L 10/16/2019 - 02:14:24: [SM]   [0] IsClientInGame
L 10/16/2019 - 02:14:24: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 02:14:24: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 02:19:05: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 02:19:05: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 02:19:05: [SM] Call stack trace:
L 10/16/2019 - 02:19:05: [SM]   [0] SetEntProp
L 10/16/2019 - 02:19:05: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 02:20:51: [SM] Exception reported: Client 4 is not in game
L 10/16/2019 - 02:20:51: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:20:51: [SM] Call stack trace:
L 10/16/2019 - 02:20:51: [SM]   [0] GetClientTeam
L 10/16/2019 - 02:20:51: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:20:53: [SM] Exception reported: Client 4 is not in game
L 10/16/2019 - 02:20:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:20:53: [SM] Call stack trace:
L 10/16/2019 - 02:20:53: [SM]   [0] GetClientTeam
L 10/16/2019 - 02:20:53: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:23:13: [SM] Exception reported: Entity 6 (6) is invalid
L 10/16/2019 - 02:23:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:23:13: [SM] Call stack trace:
L 10/16/2019 - 02:23:13: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 02:23:13: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:23:48: [SM] Exception reported: Client 5 is not in game
L 10/16/2019 - 02:23:48: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:23:48: [SM] Call stack trace:
L 10/16/2019 - 02:23:48: [SM]   [0] GetClientTeam
L 10/16/2019 - 02:23:48: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:23:48: [SM] Exception reported: Client 10 is not in game
L 10/16/2019 - 02:23:48: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:23:48: [SM] Call stack trace:
L 10/16/2019 - 02:23:48: [SM]   [0] GetClientTeam
L 10/16/2019 - 02:23:48: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:23:48: Error log file session closed.
L 10/16/2019 - 02:23:50: SourceMod error session started
L 10/16/2019 - 02:23:50: Info (map "c2m3_coaster") (file "errors_20191016.log")
L 10/16/2019 - 02:23:50: [SM] Exception reported: Client 1 is not in game
L 10/16/2019 - 02:23:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:23:50: [SM] Call stack trace:
L 10/16/2019 - 02:23:50: [SM]   [0] GetClientTeam
L 10/16/2019 - 02:23:50: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:29:11: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 02:29:11: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 02:29:11: [SM] Call stack trace:
L 10/16/2019 - 02:29:11: [SM]   [0] SetEntProp
L 10/16/2019 - 02:29:11: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 02:40:36: [SM] Exception reported: Array index out-of-bounds (index 10, limit 10)
L 10/16/2019 - 02:40:36: [SM] Blaming: l4d2_playstats.smx
L 10/16/2019 - 02:40:36: [SM] Call stack trace:
L 10/16/2019 - 02:40:36: [SM]   [1] Line 5650, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::BuildConsoleBufferFriendlyFireTaken
L 10/16/2019 - 02:40:36: [SM]   [2] Line 4452, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::DisplayStatsFriendlyFire
L 10/16/2019 - 02:40:36: [SM]   [3] Line 6443, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::AutomaticPrintPerClient
L 10/16/2019 - 02:40:36: [SM]   [4] Line 6536, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_playstats.sp::Timer_DelayedPrint
L 10/16/2019 - 02:40:56: Error log file session closed.
L 10/16/2019 - 02:43:57: SourceMod error session started
L 10/16/2019 - 02:43:57: Info (map "c2m4_barns") (file "errors_20191016.log")
L 10/16/2019 - 02:43:57: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 02:43:57: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 02:43:57: [SM] Call stack trace:
L 10/16/2019 - 02:43:57: [SM]   [0] SetEntProp
L 10/16/2019 - 02:43:57: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 02:46:57: [SM] Exception reported: Client index 331 is invalid
L 10/16/2019 - 02:46:57: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 02:46:57: [SM] Call stack trace:
L 10/16/2019 - 02:46:57: [SM]   [0] IsClientInGame
L 10/16/2019 - 02:46:57: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 02:46:57: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 02:47:00: [SM] Exception reported: Client index 331 is invalid
L 10/16/2019 - 02:47:00: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 02:47:00: [SM] Call stack trace:
L 10/16/2019 - 02:47:00: [SM]   [0] IsClientInGame
L 10/16/2019 - 02:47:00: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 02:47:00: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 02:51:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 02:51:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 02:51:01: [SM] Call stack trace:
L 10/16/2019 - 02:51:01: [SM]   [0] SetEntProp
L 10/16/2019 - 02:51:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 02:51:27: Error log file session closed.
L 10/16/2019 - 02:53:12: SourceMod error session started
L 10/16/2019 - 02:53:12: Info (map "c2m5_concert") (file "errors_20191016.log")
L 10/16/2019 - 02:53:12: [SM] Exception reported: Client index 298 is invalid
L 10/16/2019 - 02:53:12: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 02:53:12: [SM] Call stack trace:
L 10/16/2019 - 02:53:12: [SM]   [0] IsClientInGame
L 10/16/2019 - 02:53:12: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 02:53:12: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 02:53:30: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 02:53:30: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 02:53:30: [SM] Call stack trace:
L 10/16/2019 - 02:53:30: [SM]   [0] SetEntProp
L 10/16/2019 - 02:53:30: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 02:55:29: [SM] Exception reported: Client index 502 is invalid
L 10/16/2019 - 02:55:29: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 02:55:29: [SM] Call stack trace:
L 10/16/2019 - 02:55:29: [SM]   [0] IsClientInGame
L 10/16/2019 - 02:55:29: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 02:55:29: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 02:56:34: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 02:56:34: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 02:56:34: [SM] Call stack trace:
L 10/16/2019 - 02:56:34: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 02:56:34: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 02:56:35: Error log file session closed.
L 10/16/2019 - 03:02:18: SourceMod error session started
L 10/16/2019 - 03:02:18: Info (map "c4m1_milltown_a") (file "errors_20191016.log")
L 10/16/2019 - 03:02:18: [SM] Exception reported: Client 4 is not in game
L 10/16/2019 - 03:02:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 03:02:18: [SM] Call stack trace:
L 10/16/2019 - 03:02:18: [SM]   [0] GetClientTeam
L 10/16/2019 - 03:02:18: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 03:04:39: Error log file session closed.
L 10/16/2019 - 03:06:40: SourceMod error session started
L 10/16/2019 - 03:06:40: Info (map "c4m2_sugarmill_a") (file "errors_20191016.log")
L 10/16/2019 - 03:06:40: [SM] Exception reported: Client index 229 is invalid
L 10/16/2019 - 03:06:40: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 03:06:40: [SM] Call stack trace:
L 10/16/2019 - 03:06:40: [SM]   [0] IsClientInGame
L 10/16/2019 - 03:06:40: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 03:06:40: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 03:14:10: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 03:14:10: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 03:14:10: [SM] Call stack trace:
L 10/16/2019 - 03:14:10: [SM]   [0] SetEntProp
L 10/16/2019 - 03:14:10: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 03:18:00: [SM] Exception reported: Client index 760 is invalid
L 10/16/2019 - 03:18:00: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 03:18:00: [SM] Call stack trace:
L 10/16/2019 - 03:18:00: [SM]   [0] IsClientInGame
L 10/16/2019 - 03:18:00: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 03:18:00: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 03:19:33: [SM] Exception reported: Client index 759 is invalid
L 10/16/2019 - 03:19:33: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 03:19:33: [SM] Call stack trace:
L 10/16/2019 - 03:19:33: [SM]   [0] IsClientInGame
L 10/16/2019 - 03:19:33: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 03:19:33: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 03:19:38: [SM] Exception reported: Client index 759 is invalid
L 10/16/2019 - 03:19:38: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 03:19:38: [SM] Call stack trace:
L 10/16/2019 - 03:19:38: [SM]   [0] IsClientInGame
L 10/16/2019 - 03:19:38: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 03:19:38: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 03:19:39: [SM] Exception reported: Client index 759 is invalid
L 10/16/2019 - 03:19:39: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 03:19:39: [SM] Call stack trace:
L 10/16/2019 - 03:19:39: [SM]   [0] IsClientInGame
L 10/16/2019 - 03:19:39: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 03:19:39: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 03:20:08: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 03:20:08: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 03:20:08: [SM] Call stack trace:
L 10/16/2019 - 03:20:08: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 03:20:08: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 03:20:09: Error log file session closed.
L 10/16/2019 - 03:33:10: SourceMod error session started
L 10/16/2019 - 03:33:10: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 03:33:10: [CRASH] Accelerator uploaded crash dump: Crash ID: PYEH-OGKT-U6YC
L 10/16/2019 - 13:42:12: Error log file session closed.
L 10/16/2019 - 13:45:29: SourceMod error session started
L 10/16/2019 - 13:45:29: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 13:45:29: [CRASH] Accelerator uploaded crash dump: Crash ID: XLSV-7BPU-YYY4
L 10/16/2019 - 14:08:55: Error log file session closed.
L 10/16/2019 - 14:18:46: SourceMod error session started
L 10/16/2019 - 14:18:46: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 14:18:46: [SM] Exception reported: Client index 250 is invalid
L 10/16/2019 - 14:18:46: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 14:18:46: [SM] Call stack trace:
L 10/16/2019 - 14:18:46: [SM]   [0] IsClientInGame
L 10/16/2019 - 14:18:46: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 14:18:46: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 14:27:10: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 14:27:10: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 14:27:10: [SM] Call stack trace:
L 10/16/2019 - 14:27:10: [SM]   [0] SetEntProp
L 10/16/2019 - 14:27:10: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 14:27:57: Error log file session closed.
L 10/16/2019 - 14:32:17: SourceMod error session started
L 10/16/2019 - 14:32:17: Info (map "c2m2_fairgrounds") (file "errors_20191016.log")
L 10/16/2019 - 14:32:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 14:32:17: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 14:32:17: [SM] Call stack trace:
L 10/16/2019 - 14:32:17: [SM]   [0] SetEntProp
L 10/16/2019 - 14:32:17: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 14:45:04: Error log file session closed.
L 10/16/2019 - 14:52:07: SourceMod error session started
L 10/16/2019 - 14:52:07: Info (map "c2m3_coaster") (file "errors_20191016.log")
L 10/16/2019 - 14:52:07: [SM] Exception reported: Client index 157 is invalid
L 10/16/2019 - 14:52:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 14:52:07: [SM] Call stack trace:
L 10/16/2019 - 14:52:07: [SM]   [0] IsClientInGame
L 10/16/2019 - 14:52:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 14:52:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 14:55:24: Error log file session closed.
L 10/16/2019 - 15:04:50: SourceMod error session started
L 10/16/2019 - 15:04:50: Info (map "c2m4_barns") (file "errors_20191016.log")
L 10/16/2019 - 15:04:50: [SM] Exception reported: Entity 11 (11) is invalid
L 10/16/2019 - 15:04:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:04:50: [SM] Call stack trace:
L 10/16/2019 - 15:04:50: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 15:04:50: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 15:04:51: Error log file session closed.
L 10/16/2019 - 15:12:21: SourceMod error session started
L 10/16/2019 - 15:12:21: Info (map "c2m5_concert") (file "errors_20191016.log")
L 10/16/2019 - 15:12:21: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:12:21: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:12:21: [SM] Call stack trace:
L 10/16/2019 - 15:12:21: [SM]   [0] SetEntProp
L 10/16/2019 - 15:12:21: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:16:15: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:16:15: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:16:15: [SM] Call stack trace:
L 10/16/2019 - 15:16:15: [SM]   [0] SetEntProp
L 10/16/2019 - 15:16:15: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:23:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:23:17: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:23:17: [SM] Call stack trace:
L 10/16/2019 - 15:23:17: [SM]   [0] SetEntProp
L 10/16/2019 - 15:23:17: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:23:28: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:23:28: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:23:28: [SM] Call stack trace:
L 10/16/2019 - 15:23:28: [SM]   [0] SetEntProp
L 10/16/2019 - 15:23:28: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:24:12: [SM] Exception reported: Entity 6 (6) is invalid
L 10/16/2019 - 15:24:12: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:24:12: [SM] Call stack trace:
L 10/16/2019 - 15:24:12: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 15:24:12: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 15:24:14: Error log file session closed.
L 10/16/2019 - 15:24:21: SourceMod error session started
L 10/16/2019 - 15:24:21: Info (map "c5m1_waterfront") (file "errors_20191016.log")
L 10/16/2019 - 15:24:21: [SM] Exception reported: Client 8 is not in game
L 10/16/2019 - 15:24:21: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:24:21: [SM] Call stack trace:
L 10/16/2019 - 15:24:21: [SM]   [0] GetClientTeam
L 10/16/2019 - 15:24:21: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 15:28:26: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 15:28:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:28:26: [SM] Call stack trace:
L 10/16/2019 - 15:28:26: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 15:28:26: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 15:29:01: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:29:01: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:29:01: [SM] Call stack trace:
L 10/16/2019 - 15:29:01: [SM]   [0] SetEntProp
L 10/16/2019 - 15:29:01: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:33:12: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:33:12: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:33:12: [SM] Call stack trace:
L 10/16/2019 - 15:33:12: [SM]   [0] SetEntProp
L 10/16/2019 - 15:33:12: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:33:44: Error log file session closed.
L 10/16/2019 - 15:33:58: SourceMod error session started
L 10/16/2019 - 15:33:58: Info (map "c5m2_park") (file "errors_20191016.log")
L 10/16/2019 - 15:33:58: [SM] Exception reported: Client 1 is not in game
L 10/16/2019 - 15:33:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:33:58: [SM] Call stack trace:
L 10/16/2019 - 15:33:58: [SM]   [0] GetClientTeam
L 10/16/2019 - 15:33:58: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 15:46:23: Error log file session closed.
L 10/16/2019 - 15:50:17: SourceMod error session started
L 10/16/2019 - 15:50:17: Info (map "c5m3_cemetery") (file "errors_20191016.log")
L 10/16/2019 - 15:50:17: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:50:17: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:50:17: [SM] Call stack trace:
L 10/16/2019 - 15:50:17: [SM]   [0] SetEntProp
L 10/16/2019 - 15:50:17: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:51:20: Error log file session closed.
L 10/16/2019 - 15:54:17: SourceMod error session started
L 10/16/2019 - 15:54:17: Info (map "c5m4_quarter") (file "errors_20191016.log")
L 10/16/2019 - 15:54:17: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 15:54:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:54:17: [SM] Call stack trace:
L 10/16/2019 - 15:54:17: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 15:54:17: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 15:55:24: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:55:24: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:55:24: [SM] Call stack trace:
L 10/16/2019 - 15:55:24: [SM]   [0] SetEntProp
L 10/16/2019 - 15:55:24: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:55:43: Error log file session closed.
L 10/16/2019 - 15:57:23: SourceMod error session started
L 10/16/2019 - 15:57:23: Info (map "c5m5_bridge") (file "errors_20191016.log")
L 10/16/2019 - 15:57:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 15:57:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 15:57:23: [SM] Call stack trace:
L 10/16/2019 - 15:57:23: [SM]   [0] SetEntProp
L 10/16/2019 - 15:57:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 15:58:29: [SM] Exception reported: Entity 5 (5) is invalid
L 10/16/2019 - 15:58:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 15:58:29: [SM] Call stack trace:
L 10/16/2019 - 15:58:29: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 15:58:29: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 16:00:53: Error log file session closed.
L 10/16/2019 - 16:17:54: SourceMod error session started
L 10/16/2019 - 16:17:54: Info (map "c1m2_streets") (file "errors_20191016.log")
L 10/16/2019 - 16:17:54: [SM] Exception reported: Client 1 is not in game
L 10/16/2019 - 16:17:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 16:17:54: [SM] Call stack trace:
L 10/16/2019 - 16:17:54: [SM]   [0] GetClientTeam
L 10/16/2019 - 16:17:54: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 16:17:55: Error log file session closed.
L 10/16/2019 - 16:31:59: SourceMod error session started
L 10/16/2019 - 16:31:59: Info (map "c1m3_mall") (file "errors_20191016.log")
L 10/16/2019 - 16:31:59: [SM] Exception reported: Client 8 is not in game
L 10/16/2019 - 16:31:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 16:31:59: [SM] Call stack trace:
L 10/16/2019 - 16:31:59: [SM]   [0] GetClientTeam
L 10/16/2019 - 16:31:59: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 16:31:59: [SM] Exception reported: Client 9 is not in game
L 10/16/2019 - 16:31:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 16:31:59: [SM] Call stack trace:
L 10/16/2019 - 16:31:59: [SM]   [0] GetClientTeam
L 10/16/2019 - 16:31:59: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 16:31:59: [SM] Exception reported: Client 11 is not in game
L 10/16/2019 - 16:31:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 16:31:59: [SM] Call stack trace:
L 10/16/2019 - 16:31:59: [SM]   [0] GetClientTeam
L 10/16/2019 - 16:31:59: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 16:32:00: Error log file session closed.
L 10/16/2019 - 16:36:06: SourceMod error session started
L 10/16/2019 - 16:36:06: Info (map "c1m4_atrium") (file "errors_20191016.log")
L 10/16/2019 - 16:36:06: [SM] Exception reported: Client index 494 is invalid
L 10/16/2019 - 16:36:06: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 16:36:06: [SM] Call stack trace:
L 10/16/2019 - 16:36:06: [SM]   [0] IsClientInGame
L 10/16/2019 - 16:36:06: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 16:36:06: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 16:36:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 16:36:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 16:36:51: [SM] Call stack trace:
L 10/16/2019 - 16:36:51: [SM]   [0] SetEntProp
L 10/16/2019 - 16:36:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 16:38:49: [SM] Exception reported: Client index 333 is invalid
L 10/16/2019 - 16:38:49: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 16:38:49: [SM] Call stack trace:
L 10/16/2019 - 16:38:49: [SM]   [0] IsClientInGame
L 10/16/2019 - 16:38:49: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 16:38:49: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 16:40:13: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 16:40:13: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 16:40:13: [SM] Call stack trace:
L 10/16/2019 - 16:40:13: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 16:40:13: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 16:40:14: Error log file session closed.
L 10/16/2019 - 16:56:03: SourceMod error session started
L 10/16/2019 - 16:56:03: Info (map "c3m2_swamp") (file "errors_20191016.log")
L 10/16/2019 - 16:56:03: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 16:56:03: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 16:56:03: [SM] Call stack trace:
L 10/16/2019 - 16:56:03: [SM]   [0] SetEntProp
L 10/16/2019 - 16:56:03: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 16:56:26: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 16:56:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 16:56:26: [SM] Call stack trace:
L 10/16/2019 - 16:56:26: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 16:56:26: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 17:00:28: [SM] Exception reported: Client 7 is not in game
L 10/16/2019 - 17:00:28: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:00:28: [SM] Call stack trace:
L 10/16/2019 - 17:00:28: [SM]   [0] GetClientTeam
L 10/16/2019 - 17:00:28: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:00:30: Error log file session closed.
L 10/16/2019 - 17:06:29: SourceMod error session started
L 10/16/2019 - 17:06:29: Info (map "c3m3_shantytown") (file "errors_20191016.log")
L 10/16/2019 - 17:06:29: [SM] Exception reported: Client index 403 is invalid
L 10/16/2019 - 17:06:29: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 17:06:29: [SM] Call stack trace:
L 10/16/2019 - 17:06:29: [SM]   [0] IsClientInGame
L 10/16/2019 - 17:06:29: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 17:06:29: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 17:06:32: [SM] Exception reported: Client index 403 is invalid
L 10/16/2019 - 17:06:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 17:06:32: [SM] Call stack trace:
L 10/16/2019 - 17:06:32: [SM]   [0] IsClientInGame
L 10/16/2019 - 17:06:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 17:06:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 17:08:36: Error log file session closed.
L 10/16/2019 - 17:11:18: SourceMod error session started
L 10/16/2019 - 17:11:18: Info (map "c3m4_plantation") (file "errors_20191016.log")
L 10/16/2019 - 17:11:18: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 17:11:18: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 17:11:18: [SM] Call stack trace:
L 10/16/2019 - 17:11:18: [SM]   [0] SetEntProp
L 10/16/2019 - 17:11:18: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 17:11:20: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 17:11:20: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 17:11:20: [SM] Call stack trace:
L 10/16/2019 - 17:11:20: [SM]   [0] SetEntProp
L 10/16/2019 - 17:11:20: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 17:15:27: [SM] Exception reported: Client 9 is not in game
L 10/16/2019 - 17:15:27: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:15:27: [SM] Call stack trace:
L 10/16/2019 - 17:15:27: [SM]   [0] GetClientTeam
L 10/16/2019 - 17:15:27: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:15:29: Error log file session closed.
L 10/16/2019 - 17:18:20: SourceMod error session started
L 10/16/2019 - 17:18:20: Info (map "c7m1_docks") (file "errors_20191016.log")
L 10/16/2019 - 17:18:20: [SM] Exception reported: Client 9 is not in game
L 10/16/2019 - 17:18:20: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:18:20: [SM] Call stack trace:
L 10/16/2019 - 17:18:20: [SM]   [0] GetClientTeam
L 10/16/2019 - 17:18:20: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:18:39: [SM] Exception reported: Client 8 is not in game
L 10/16/2019 - 17:18:39: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:18:39: [SM] Call stack trace:
L 10/16/2019 - 17:18:39: [SM]   [0] GetClientTeam
L 10/16/2019 - 17:18:39: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:27:54: [SM] Exception reported: Entity 5 (5) is invalid
L 10/16/2019 - 17:27:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:27:54: [SM] Call stack trace:
L 10/16/2019 - 17:27:54: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 17:27:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:27:54: [SM] Exception reported: Entity 4 (4) is invalid
L 10/16/2019 - 17:27:54: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:27:54: [SM] Call stack trace:
L 10/16/2019 - 17:27:54: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 17:27:54: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:27:56: Error log file session closed.
L 10/16/2019 - 17:30:07: SourceMod error session started
L 10/16/2019 - 17:30:07: Info (map "c7m2_barge") (file "errors_20191016.log")
L 10/16/2019 - 17:30:07: [SM] Exception reported: Client index 335 is invalid
L 10/16/2019 - 17:30:07: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 17:30:07: [SM] Call stack trace:
L 10/16/2019 - 17:30:07: [SM]   [0] IsClientInGame
L 10/16/2019 - 17:30:07: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 17:30:07: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 17:39:32: Error log file session closed.
L 10/16/2019 - 17:46:30: SourceMod error session started
L 10/16/2019 - 17:46:30: Info (map "c7m3_port") (file "errors_20191016.log")
L 10/16/2019 - 17:46:30: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 17:46:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 17:46:30: [SM] Call stack trace:
L 10/16/2019 - 17:46:30: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 17:46:30: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 17:46:31: Error log file session closed.
L 10/16/2019 - 17:59:23: SourceMod error session started
L 10/16/2019 - 17:59:23: Info (map "c1m2_streets") (file "errors_20191016.log")
L 10/16/2019 - 17:59:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 17:59:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 17:59:23: [SM] Call stack trace:
L 10/16/2019 - 17:59:23: [SM]   [0] SetEntProp
L 10/16/2019 - 17:59:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 18:04:29: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 18:04:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:04:29: [SM] Call stack trace:
L 10/16/2019 - 18:04:29: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:04:29: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 18:09:50: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 18:09:50: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 18:09:50: [SM] Call stack trace:
L 10/16/2019 - 18:09:50: [SM]   [0] SetEntProp
L 10/16/2019 - 18:09:50: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 18:12:31: [SM] Exception reported: Entity 11 (11) is invalid
L 10/16/2019 - 18:12:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:12:31: [SM] Call stack trace:
L 10/16/2019 - 18:12:31: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:12:31: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 18:12:31: [SM] Exception reported: Client 6 is not in game
L 10/16/2019 - 18:12:31: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:12:31: [SM] Call stack trace:
L 10/16/2019 - 18:12:31: [SM]   [0] GetClientTeam
L 10/16/2019 - 18:12:31: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 18:12:32: Error log file session closed.
L 10/16/2019 - 18:22:10: SourceMod error session started
L 10/16/2019 - 18:22:10: Info (map "c1m3_mall") (file "errors_20191016.log")
L 10/16/2019 - 18:22:10: [SM] Exception reported: Entity 10 (10) is invalid
L 10/16/2019 - 18:22:10: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:22:10: [SM] Call stack trace:
L 10/16/2019 - 18:22:10: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:22:10: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 18:28:09: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 18:28:09: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 18:28:09: [SM] Call stack trace:
L 10/16/2019 - 18:28:09: [SM]   [0] SetEntProp
L 10/16/2019 - 18:28:09: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 18:28:35: Error log file session closed.
L 10/16/2019 - 18:35:41: SourceMod error session started
L 10/16/2019 - 18:35:41: Info (map "c1m4_atrium") (file "errors_20191016.log")
L 10/16/2019 - 18:35:41: [SM] Exception reported: Client index 274 is invalid
L 10/16/2019 - 18:35:41: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 18:35:41: [SM] Call stack trace:
L 10/16/2019 - 18:35:41: [SM]   [0] IsClientInGame
L 10/16/2019 - 18:35:41: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 18:35:41: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 18:37:26: [SM] Exception reported: Entity 4 (4) is invalid
L 10/16/2019 - 18:37:26: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:37:26: [SM] Call stack trace:
L 10/16/2019 - 18:37:26: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:37:26: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 18:37:27: Error log file session closed.
L 10/16/2019 - 18:44:43: SourceMod error session started
L 10/16/2019 - 18:44:43: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 18:44:43: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 18:44:43: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:44:43: [SM] Call stack trace:
L 10/16/2019 - 18:44:43: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:44:43: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 18:45:53: [SM] Exception reported: Client 6 is not in game
L 10/16/2019 - 18:45:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:45:53: [SM] Call stack trace:
L 10/16/2019 - 18:45:53: [SM]   [0] GetClientTeam
L 10/16/2019 - 18:45:53: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 18:52:51: [SM] Exception reported: Entity 8 (8) is invalid
L 10/16/2019 - 18:52:51: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:52:51: [SM] Call stack trace:
L 10/16/2019 - 18:52:51: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:52:51: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 18:52:51: [SM] Exception reported: Entity 4 (4) is invalid
L 10/16/2019 - 18:52:51: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 18:52:51: [SM] Call stack trace:
L 10/16/2019 - 18:52:51: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 18:52:51: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 18:52:51: Error log file session closed.
L 10/16/2019 - 18:57:56: SourceMod error session started
L 10/16/2019 - 18:57:56: Info (map "c2m2_fairgrounds") (file "errors_20191016.log")
L 10/16/2019 - 18:57:56: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 18:57:56: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 18:57:56: [SM] Call stack trace:
L 10/16/2019 - 18:57:56: [SM]   [0] SetEntProp
L 10/16/2019 - 18:57:56: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 19:01:30: [SM] Exception reported: Client 3 is not in game
L 10/16/2019 - 19:01:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:01:30: [SM] Call stack trace:
L 10/16/2019 - 19:01:30: [SM]   [0] GetClientTeam
L 10/16/2019 - 19:01:30: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 19:01:51: [SM] Exception reported: Client 3 is not in game
L 10/16/2019 - 19:01:51: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:01:51: [SM] Call stack trace:
L 10/16/2019 - 19:01:51: [SM]   [0] GetClientTeam
L 10/16/2019 - 19:01:51: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 19:02:29: [SM] Exception reported: Client 3 is not in game
L 10/16/2019 - 19:02:29: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:02:29: [SM] Call stack trace:
L 10/16/2019 - 19:02:29: [SM]   [0] GetClientTeam
L 10/16/2019 - 19:02:29: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 19:03:35: Error log file session closed.
L 10/16/2019 - 19:27:00: SourceMod error session started
L 10/16/2019 - 19:27:00: Info (map "c2m3_coaster") (file "errors_20191016.log")
L 10/16/2019 - 19:27:00: [SM] Exception reported: Entity 10 (10) is invalid
L 10/16/2019 - 19:27:00: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:27:00: [SM] Call stack trace:
L 10/16/2019 - 19:27:00: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 19:27:00: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 19:27:01: Error log file session closed.
L 10/16/2019 - 19:29:43: SourceMod error session started
L 10/16/2019 - 19:29:43: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 19:29:43: [CRASH] Accelerator uploaded crash dump: Crash ID: 46PM-C6SE-FHRI
L 10/16/2019 - 19:32:38: Error log file session closed.
L 10/16/2019 - 19:36:06: SourceMod error session started
L 10/16/2019 - 19:36:06: Info (map "c5m1_waterfront") (file "errors_20191016.log")
L 10/16/2019 - 19:36:06: [SM] Exception reported: Client index 407 is invalid
L 10/16/2019 - 19:36:06: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:36:06: [SM] Call stack trace:
L 10/16/2019 - 19:36:06: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:36:06: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:36:06: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:36:14: [SM] Exception reported: Client index 407 is invalid
L 10/16/2019 - 19:36:14: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:36:14: [SM] Call stack trace:
L 10/16/2019 - 19:36:14: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:36:14: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:36:14: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:36:23: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 19:36:23: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 19:36:23: [SM] Call stack trace:
L 10/16/2019 - 19:36:23: [SM]   [0] SetEntProp
L 10/16/2019 - 19:36:23: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 19:36:26: [SM] Exception reported: Client index 407 is invalid
L 10/16/2019 - 19:36:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:36:26: [SM] Call stack trace:
L 10/16/2019 - 19:36:26: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:36:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:36:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:32: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:32: [SM] Call stack trace:
L 10/16/2019 - 19:40:32: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:32: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:32: [SM] Call stack trace:
L 10/16/2019 - 19:40:32: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:32: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:32: [SM] Call stack trace:
L 10/16/2019 - 19:40:32: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:32: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:32: [SM] Call stack trace:
L 10/16/2019 - 19:40:32: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:33: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:33: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:33: [SM] Call stack trace:
L 10/16/2019 - 19:40:33: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:33: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:33: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:40:43: [SM] Exception reported: Client index 389 is invalid
L 10/16/2019 - 19:40:43: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 19:40:43: [SM] Call stack trace:
L 10/16/2019 - 19:40:43: [SM]   [0] IsClientInGame
L 10/16/2019 - 19:40:43: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 19:40:43: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 19:41:07: [SM] Exception reported: Client 7 is not in game
L 10/16/2019 - 19:41:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:41:07: [SM] Call stack trace:
L 10/16/2019 - 19:41:07: [SM]   [0] GetClientTeam
L 10/16/2019 - 19:41:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 19:41:07: [SM] Exception reported: Client 10 is not in game
L 10/16/2019 - 19:41:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:41:07: [SM] Call stack trace:
L 10/16/2019 - 19:41:07: [SM]   [0] GetClientTeam
L 10/16/2019 - 19:41:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 19:41:07: [SM] Exception reported: Entity 9 (9) is invalid
L 10/16/2019 - 19:41:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:41:07: [SM] Call stack trace:
L 10/16/2019 - 19:41:07: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 19:41:07: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 19:41:07: Error log file session closed.
L 10/16/2019 - 19:57:11: SourceMod error session started
L 10/16/2019 - 19:57:11: Info (map "c5m2_park") (file "errors_20191016.log")
L 10/16/2019 - 19:57:11: [SM] Exception reported: Entity 9 (9) is invalid
L 10/16/2019 - 19:57:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 19:57:11: [SM] Call stack trace:
L 10/16/2019 - 19:57:11: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 19:57:11: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 19:57:13: Error log file session closed.
L 10/16/2019 - 20:00:58: SourceMod error session started
L 10/16/2019 - 20:00:58: Info (map "c5m3_cemetery") (file "errors_20191016.log")
L 10/16/2019 - 20:00:58: [SM] Exception reported: Entity 11 (11) is invalid
L 10/16/2019 - 20:00:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:00:58: [SM] Call stack trace:
L 10/16/2019 - 20:00:58: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:00:58: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 20:03:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 20:03:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 20:03:25: [SM] Call stack trace:
L 10/16/2019 - 20:03:25: [SM]   [0] SetEntProp
L 10/16/2019 - 20:03:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 20:06:38: [SM] Exception reported: Client index 579 is invalid
L 10/16/2019 - 20:06:38: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 20:06:38: [SM] Call stack trace:
L 10/16/2019 - 20:06:38: [SM]   [0] IsClientInGame
L 10/16/2019 - 20:06:38: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 20:06:38: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 20:11:04: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 20:11:04: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:11:04: [SM] Call stack trace:
L 10/16/2019 - 20:11:04: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:11:04: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:11:05: Error log file session closed.
L 10/16/2019 - 20:25:44: SourceMod error session started
L 10/16/2019 - 20:25:44: Info (map "c5m5_bridge") (file "errors_20191016.log")
L 10/16/2019 - 20:25:44: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 20:25:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:25:44: [SM] Call stack trace:
L 10/16/2019 - 20:25:44: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:25:44: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:25:45: Error log file session closed.
L 10/16/2019 - 20:25:49: SourceMod error session started
L 10/16/2019 - 20:25:49: Info (map "c1m1_hotel") (file "errors_20191016.log")
L 10/16/2019 - 20:25:49: [SM] Exception reported: Client 2 is not in game
L 10/16/2019 - 20:25:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:25:49: [SM] Call stack trace:
L 10/16/2019 - 20:25:49: [SM]   [0] GetClientTeam
L 10/16/2019 - 20:25:49: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:25:50: [SM] Exception reported: Client 6 is not in game
L 10/16/2019 - 20:25:50: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:25:50: [SM] Call stack trace:
L 10/16/2019 - 20:25:50: [SM]   [0] GetClientTeam
L 10/16/2019 - 20:25:50: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:26:07: [SM] Exception reported: Client 4 is not in game
L 10/16/2019 - 20:26:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:26:07: [SM] Call stack trace:
L 10/16/2019 - 20:26:07: [SM]   [0] GetClientTeam
L 10/16/2019 - 20:26:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:26:07: [SM] Exception reported: Client 7 is not in game
L 10/16/2019 - 20:26:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:26:07: [SM] Call stack trace:
L 10/16/2019 - 20:26:07: [SM]   [0] GetClientTeam
L 10/16/2019 - 20:26:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:26:07: [SM] Exception reported: Client 9 is not in game
L 10/16/2019 - 20:26:07: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:26:07: [SM] Call stack trace:
L 10/16/2019 - 20:26:07: [SM]   [0] GetClientTeam
L 10/16/2019 - 20:26:07: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:26:07: Error log file session closed.
L 10/16/2019 - 20:30:38: SourceMod error session started
L 10/16/2019 - 20:30:38: Info (map "c10m1_caves") (file "errors_20191016.log")
L 10/16/2019 - 20:30:38: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 20:30:38: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 20:30:38: [SM] Call stack trace:
L 10/16/2019 - 20:30:38: [SM]   [0] SetEntProp
L 10/16/2019 - 20:30:38: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 20:35:56: [SM] Exception reported: Entity 5 (5) is invalid
L 10/16/2019 - 20:35:56: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:35:56: [SM] Call stack trace:
L 10/16/2019 - 20:35:56: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:35:56: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:35:57: Error log file session closed.
L 10/16/2019 - 20:38:51: SourceMod error session started
L 10/16/2019 - 20:38:51: Info (map "c10m2_drainage") (file "errors_20191016.log")
L 10/16/2019 - 20:38:51: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 20:38:51: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 20:38:51: [SM] Call stack trace:
L 10/16/2019 - 20:38:51: [SM]   [0] SetEntProp
L 10/16/2019 - 20:38:51: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 20:41:49: Error log file session closed.
L 10/16/2019 - 20:45:12: SourceMod error session started
L 10/16/2019 - 20:45:12: Info (map "c10m3_ranchhouse") (file "errors_20191016.log")
L 10/16/2019 - 20:45:12: [SM] Exception reported: Client index 151 is invalid
L 10/16/2019 - 20:45:12: [SM] Blaming: l4d2_getup_slide_fix.smx
L 10/16/2019 - 20:45:12: [SM] Call stack trace:
L 10/16/2019 - 20:45:12: [SM]   [0] IsClientInGame
L 10/16/2019 - 20:45:12: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 10/16/2019 - 20:45:12: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 10/16/2019 - 20:45:58: [SM] Exception reported: Entity 6 (6) is invalid
L 10/16/2019 - 20:45:58: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:45:58: [SM] Call stack trace:
L 10/16/2019 - 20:45:58: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:45:58: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 20:56:55: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 20:56:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:56:55: [SM] Call stack trace:
L 10/16/2019 - 20:56:55: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:56:55: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:56:55: [SM] Exception reported: Client 6 is not in game
L 10/16/2019 - 20:56:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:56:55: [SM] Call stack trace:
L 10/16/2019 - 20:56:55: [SM]   [0] GetClientTeam
L 10/16/2019 - 20:56:55: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:56:55: [SM] Exception reported: Entity 3 (3) is invalid
L 10/16/2019 - 20:56:55: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 20:56:55: [SM] Call stack trace:
L 10/16/2019 - 20:56:55: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 20:56:55: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 20:56:55: Error log file session closed.
L 10/16/2019 - 21:13:59: SourceMod error session started
L 10/16/2019 - 21:13:59: Info (map "c10m4_mainstreet") (file "errors_20191016.log")
L 10/16/2019 - 21:13:59: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 21:13:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:13:59: [SM] Call stack trace:
L 10/16/2019 - 21:13:59: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:13:59: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 21:13:59: Error log file session closed.
L 10/16/2019 - 21:15:45: SourceMod error session started
L 10/16/2019 - 21:15:45: Info (map "c10m5_houseboat") (file "errors_20191016.log")
L 10/16/2019 - 21:15:45: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 21:15:45: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 21:15:45: [SM] Call stack trace:
L 10/16/2019 - 21:15:45: [SM]   [0] SetEntProp
L 10/16/2019 - 21:15:45: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 21:29:17: [SM] Exception reported: Entity 2 (2) is invalid
L 10/16/2019 - 21:29:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:29:17: [SM] Call stack trace:
L 10/16/2019 - 21:29:17: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:29:17: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 21:29:18: Error log file session closed.
L 10/16/2019 - 21:32:59: SourceMod error session started
L 10/16/2019 - 21:32:59: Info (map "c11m1_greenhouse") (file "errors_20191016.log")
L 10/16/2019 - 21:32:59: [SM] Exception reported: Entity 1 (1) is invalid
L 10/16/2019 - 21:32:59: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:32:59: [SM] Call stack trace:
L 10/16/2019 - 21:32:59: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:32:59: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 21:37:24: [SM] Exception reported: Entity 4 (4) is invalid
L 10/16/2019 - 21:37:24: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:37:24: [SM] Call stack trace:
L 10/16/2019 - 21:37:24: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:37:24: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 21:37:25: Error log file session closed.
L 10/16/2019 - 21:39:52: SourceMod error session started
L 10/16/2019 - 21:39:52: Info (map "c11m2_offices") (file "errors_20191016.log")
L 10/16/2019 - 21:39:52: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 21:39:52: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 21:39:52: [SM] Call stack trace:
L 10/16/2019 - 21:39:52: [SM]   [0] SetEntProp
L 10/16/2019 - 21:39:52: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 21:42:44: [SM] Exception reported: Client 8 is not in game
L 10/16/2019 - 21:42:44: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:42:44: [SM] Call stack trace:
L 10/16/2019 - 21:42:44: [SM]   [0] GetClientTeam
L 10/16/2019 - 21:42:44: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 21:43:52: [SM] Exception reported: Entity -1 (-1) is invalid
L 10/16/2019 - 21:43:52: [SM] Blaming: l4d2_melee_shenanigans.smx
L 10/16/2019 - 21:43:52: [SM] Call stack trace:
L 10/16/2019 - 21:43:52: [SM]   [0] SetEntProp
L 10/16/2019 - 21:43:52: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 10/16/2019 - 21:44:15: Error log file session closed.
L 10/16/2019 - 21:47:11: SourceMod error session started
L 10/16/2019 - 21:47:11: Info (map "c11m3_garage") (file "errors_20191016.log")
L 10/16/2019 - 21:47:11: [SM] Exception reported: Entity 6 (6) is invalid
L 10/16/2019 - 21:47:11: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:47:11: [SM] Call stack trace:
L 10/16/2019 - 21:47:11: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:47:11: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 21:55:22: [SM] Exception reported: Entity 8 (8) is invalid
L 10/16/2019 - 21:55:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:55:22: [SM] Call stack trace:
L 10/16/2019 - 21:55:22: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:55:22: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 10/16/2019 - 21:55:22: [SM] Exception reported: Entity 8 (8) is invalid
L 10/16/2019 - 21:55:22: [SM] Blaming: l4d2_charger_getup_fix.smx
L 10/16/2019 - 21:55:22: [SM] Call stack trace:
L 10/16/2019 - 21:55:22: [SM]   [0] GetEntDataEnt2
L 10/16/2019 - 21:55:22: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 10/16/2019 - 21:55:39: SourceMod error session started
L 10/16/2019 - 21:55:39: Info (map "c2m1_highway") (file "errors_20191016.log")
L 10/16/2019 - 21:55:39: [CRASH] Accelerator uploaded crash dump: Crash ID: 6BDJ-4HJ3-PGXG
