L 11/03/2019 - 14:07:08: SourceMod error session started
L 11/03/2019 - 14:07:08: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 14:07:08: Error log file session closed.
L 11/03/2019 - 17:34:45: SourceMod error session started
L 11/03/2019 - 17:34:45: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 17:34:45: [sbpp_sleuth.smx] SourceSleuth: Database connection error: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/03/2019 - 17:34:45: [sbpp_comms.smx] Connecting to database failed: [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/03/2019 - 17:34:45: [SM] Exception reported: Failed to connect to SourceBans DB, [2013]: Lost connection to MySQL server at 'reading initial communication packet', system error: 113
L 11/03/2019 - 17:34:45: [SM] Blaming: sbpp_checker.smx
L 11/03/2019 - 17:34:45: [SM] Call stack trace:
L 11/03/2019 - 17:34:45: [SM]   [0] SetFailState
L 11/03/2019 - 17:34:45: [SM]   [1] Line 75, .\sbpp_checker.sp::OnDatabaseConnected
L 11/03/2019 - 19:16:19: Error log file session closed.
L 11/03/2019 - 19:16:33: SourceMod error session started
L 11/03/2019 - 19:16:33: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 19:16:33: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:16:33: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:16:33: [SM] Call stack trace:
L 11/03/2019 - 19:16:33: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:16:33: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:16:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:16:35: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:16:35: [SM] Call stack trace:
L 11/03/2019 - 19:16:35: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:16:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:16:52: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:16:52: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:16:52: [SM] Call stack trace:
L 11/03/2019 - 19:16:52: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:16:52: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:17:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:17:05: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:17:05: [SM] Call stack trace:
L 11/03/2019 - 19:17:05: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:17:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:17:40: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:17:40: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:17:40: [SM] Call stack trace:
L 11/03/2019 - 19:17:40: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:17:40: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:18:58: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:18:58: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:18:58: [SM] Call stack trace:
L 11/03/2019 - 19:18:58: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:18:58: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:18:59: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:18:59: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:18:59: [SM] Call stack trace:
L 11/03/2019 - 19:18:59: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:18:59: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:19:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:19:47: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:19:47: [SM] Call stack trace:
L 11/03/2019 - 19:19:47: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:19:47: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:21:34: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:21:34: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:21:34: [SM] Call stack trace:
L 11/03/2019 - 19:21:34: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:21:34: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:22:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:22:29: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:22:29: [SM] Call stack trace:
L 11/03/2019 - 19:22:29: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:22:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:23:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:23:05: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:23:05: [SM] Call stack trace:
L 11/03/2019 - 19:23:05: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:23:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:24:16: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:24:16: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:24:16: [SM] Call stack trace:
L 11/03/2019 - 19:24:16: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:24:16: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:25:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:25:55: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:25:55: [SM] Call stack trace:
L 11/03/2019 - 19:25:55: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:25:55: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:27:53: [SM] Exception reported: Entity 1 (1) is invalid
L 11/03/2019 - 19:27:53: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 19:27:53: [SM] Call stack trace:
L 11/03/2019 - 19:27:53: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 19:27:53: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 19:27:56: Error log file session closed.
L 11/03/2019 - 19:28:03: SourceMod error session started
L 11/03/2019 - 19:28:03: Info (map "c2m2_fairgrounds") (file "errors_20191103.log")
L 11/03/2019 - 19:28:03: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:03: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:03: [SM] Call stack trace:
L 11/03/2019 - 19:28:03: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:03: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:05: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:05: [SM] Call stack trace:
L 11/03/2019 - 19:28:05: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:07: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:07: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:07: [SM] Call stack trace:
L 11/03/2019 - 19:28:07: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:07: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:07: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:07: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:07: [SM] Call stack trace:
L 11/03/2019 - 19:28:07: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:07: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:10: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:10: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:10: [SM] Call stack trace:
L 11/03/2019 - 19:28:10: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:10: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:11: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:11: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:11: [SM] Call stack trace:
L 11/03/2019 - 19:28:11: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:11: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:13: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:13: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:13: [SM] Call stack trace:
L 11/03/2019 - 19:28:13: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:13: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:24: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:24: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:24: [SM] Call stack trace:
L 11/03/2019 - 19:28:24: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:24: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:36: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:36: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:36: [SM] Call stack trace:
L 11/03/2019 - 19:28:36: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:36: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:28:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:28:47: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:28:47: [SM] Call stack trace:
L 11/03/2019 - 19:28:47: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:28:47: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:33:02: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:33:02: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:33:02: [SM] Call stack trace:
L 11/03/2019 - 19:33:02: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:33:02: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:33:17: [SM] Exception reported: Entity 4 (4) is invalid
L 11/03/2019 - 19:33:17: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 19:33:17: [SM] Call stack trace:
L 11/03/2019 - 19:33:17: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 19:33:17: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/03/2019 - 19:34:59: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:34:59: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:34:59: [SM] Call stack trace:
L 11/03/2019 - 19:34:59: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:34:59: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:36:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:36:29: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:36:29: [SM] Call stack trace:
L 11/03/2019 - 19:36:29: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:36:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:37:16: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:37:16: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:37:16: [SM] Call stack trace:
L 11/03/2019 - 19:37:16: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:37:16: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:37:25: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:37:25: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:37:25: [SM] Call stack trace:
L 11/03/2019 - 19:37:25: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:37:25: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:37:51: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:37:51: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:37:51: [SM] Call stack trace:
L 11/03/2019 - 19:37:51: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:37:51: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:39:23: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:39:23: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:39:23: [SM] Call stack trace:
L 11/03/2019 - 19:39:23: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:39:23: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:40:31: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:40:31: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:40:31: [SM] Call stack trace:
L 11/03/2019 - 19:40:31: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:40:31: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:40:35: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:40:35: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:40:35: [SM] Call stack trace:
L 11/03/2019 - 19:40:35: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:40:35: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:41:17: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:41:17: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:41:17: [SM] Call stack trace:
L 11/03/2019 - 19:41:17: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:41:17: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:43:01: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:43:01: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:43:01: [SM] Call stack trace:
L 11/03/2019 - 19:43:01: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:43:01: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:43:03: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:43:03: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:43:03: [SM] Call stack trace:
L 11/03/2019 - 19:43:03: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:43:03: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:43:38: Error log file session closed.
L 11/03/2019 - 19:43:46: SourceMod error session started
L 11/03/2019 - 19:43:46: Info (map "c2m3_coaster") (file "errors_20191103.log")
L 11/03/2019 - 19:43:46: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:43:46: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:43:46: [SM] Call stack trace:
L 11/03/2019 - 19:43:46: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:43:46: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:43:50: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:43:50: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:43:50: [SM] Call stack trace:
L 11/03/2019 - 19:43:50: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:43:50: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:43:51: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:43:51: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:43:51: [SM] Call stack trace:
L 11/03/2019 - 19:43:51: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:43:51: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:44:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:44:00: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:44:00: [SM] Call stack trace:
L 11/03/2019 - 19:44:00: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:44:00: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:44:21: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:44:21: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:44:21: [SM] Call stack trace:
L 11/03/2019 - 19:44:21: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:44:21: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:45:13: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:45:13: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:45:13: [SM] Call stack trace:
L 11/03/2019 - 19:45:13: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:45:13: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:49:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:49:04: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:49:04: [SM] Call stack trace:
L 11/03/2019 - 19:49:04: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:49:04: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:49:54: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/03/2019 - 19:49:54: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/03/2019 - 19:49:54: [SM] Call stack trace:
L 11/03/2019 - 19:49:54: [SM]   [0] SetEntProp
L 11/03/2019 - 19:49:54: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/03/2019 - 19:51:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:51:26: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:51:26: [SM] Call stack trace:
L 11/03/2019 - 19:51:26: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:51:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:52:54: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:52:54: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:52:54: [SM] Call stack trace:
L 11/03/2019 - 19:52:54: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:52:54: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:54:14: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:54:15: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:54:15: [SM] Call stack trace:
L 11/03/2019 - 19:54:15: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:54:15: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 19:59:38: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 19:59:38: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 19:59:38: [SM] Call stack trace:
L 11/03/2019 - 19:59:38: [SM]   [0] SQL_TQuery
L 11/03/2019 - 19:59:38: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:15: [SM] Exception reported: Entity 4 (4) is invalid
L 11/03/2019 - 20:00:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 20:00:15: [SM] Call stack trace:
L 11/03/2019 - 20:00:15: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 20:00:15: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 20:00:15: [SM] Exception reported: Entity 6 (6) is invalid
L 11/03/2019 - 20:00:15: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 20:00:15: [SM] Call stack trace:
L 11/03/2019 - 20:00:15: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 20:00:15: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 20:00:16: Error log file session closed.
L 11/03/2019 - 20:00:26: SourceMod error session started
L 11/03/2019 - 20:00:26: Info (map "c2m4_barns") (file "errors_20191103.log")
L 11/03/2019 - 20:00:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:26: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:26: [SM] Call stack trace:
L 11/03/2019 - 20:00:26: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:26: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:29: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:29: [SM] Call stack trace:
L 11/03/2019 - 20:00:29: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:31: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:31: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:31: [SM] Call stack trace:
L 11/03/2019 - 20:00:31: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:31: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:32: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:32: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:32: [SM] Call stack trace:
L 11/03/2019 - 20:00:32: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:32: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:37: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:37: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:37: [SM] Call stack trace:
L 11/03/2019 - 20:00:37: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:37: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:43: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:43: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:43: [SM] Call stack trace:
L 11/03/2019 - 20:00:43: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:43: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:00:44: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:00:44: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:00:44: [SM] Call stack trace:
L 11/03/2019 - 20:00:44: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:00:44: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:01:58: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:01:58: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:01:58: [SM] Call stack trace:
L 11/03/2019 - 20:01:58: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:01:58: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:02:05: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:02:05: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:02:05: [SM] Call stack trace:
L 11/03/2019 - 20:02:05: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:02:05: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:05:36: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:05:36: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:05:36: [SM] Call stack trace:
L 11/03/2019 - 20:05:36: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:05:36: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:06:38: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:06:38: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:06:38: [SM] Call stack trace:
L 11/03/2019 - 20:06:38: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:06:38: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:07:29: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 11/03/2019 - 20:07:29: [SM] Blaming: sbpp_sleuth.smx
L 11/03/2019 - 20:07:29: [SM] Call stack trace:
L 11/03/2019 - 20:07:29: [SM]   [0] SQL_TQuery
L 11/03/2019 - 20:07:29: [SM]   [1] Line 170, D:\MegaSync\Projects\Sourcemod\scripting\sbpp_sleuth.sp::OnClientPostAdminCheck
L 11/03/2019 - 20:09:39: [SM] Exception reported: Client index 290 is invalid
L 11/03/2019 - 20:09:39: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 20:09:39: [SM] Call stack trace:
L 11/03/2019 - 20:09:39: [SM]   [0] IsClientInGame
L 11/03/2019 - 20:09:39: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 20:09:39: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 20:09:41: [SM] Exception reported: Client index 290 is invalid
L 11/03/2019 - 20:09:41: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 20:09:41: [SM] Call stack trace:
L 11/03/2019 - 20:09:41: [SM]   [0] IsClientInGame
L 11/03/2019 - 20:09:41: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 20:09:41: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 20:09:57: [SM] Exception reported: Client index 290 is invalid
L 11/03/2019 - 20:09:57: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 20:09:57: [SM] Call stack trace:
L 11/03/2019 - 20:09:57: [SM]   [0] IsClientInGame
L 11/03/2019 - 20:09:57: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 20:09:57: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 20:12:09: SourceMod error session started
L 11/03/2019 - 20:12:09: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 20:12:09: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 20:12:09: [UPDATER] Could not download "http://update.sourcemod.net/update/"
L 11/03/2019 - 20:12:09: [UPDATER] Error: Couldn't resolve host 'update.sourcemod.net'
L 11/03/2019 - 20:12:09: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 20:15:35: [SM] Exception reported: Client 1 is not in game
L 11/03/2019 - 20:15:35: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 20:15:35: [SM] Call stack trace:
L 11/03/2019 - 20:15:35: [SM]   [0] GetClientTeam
L 11/03/2019 - 20:15:35: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 20:36:49: [SM] Exception reported: Client 1 is not in game
L 11/03/2019 - 20:36:49: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 20:36:49: [SM] Call stack trace:
L 11/03/2019 - 20:36:49: [SM]   [0] GetClientTeam
L 11/03/2019 - 20:36:49: [SM]   [1] Line 79, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 20:36:58: Error log file session closed.
L 11/03/2019 - 20:38:26: SourceMod error session started
L 11/03/2019 - 20:38:26: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 20:38:26: [SM] Exception reported: Client index 304 is invalid
L 11/03/2019 - 20:38:26: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 20:38:26: [SM] Call stack trace:
L 11/03/2019 - 20:38:26: [SM]   [0] IsClientInGame
L 11/03/2019 - 20:38:26: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 20:38:26: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 20:38:27: [SM] Exception reported: Client index 304 is invalid
L 11/03/2019 - 20:38:27: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 20:38:27: [SM] Call stack trace:
L 11/03/2019 - 20:38:27: [SM]   [0] IsClientInGame
L 11/03/2019 - 20:38:27: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 20:38:27: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 20:44:15: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/03/2019 - 20:44:15: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/03/2019 - 20:44:15: [SM] Call stack trace:
L 11/03/2019 - 20:44:15: [SM]   [0] SetEntProp
L 11/03/2019 - 20:44:15: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/03/2019 - 20:44:41: [SM] Exception reported: Entity 7 (7) is invalid
L 11/03/2019 - 20:44:41: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 20:44:41: [SM] Call stack trace:
L 11/03/2019 - 20:44:41: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 20:44:41: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 20:44:42: Error log file session closed.
L 11/03/2019 - 20:45:40: SourceMod error session started
L 11/03/2019 - 20:45:40: Info (map "c2m2_fairgrounds") (file "errors_20191103.log")
L 11/03/2019 - 20:45:40: [SM] Exception reported: Invalid edict (-1 - -1)
L 11/03/2019 - 20:45:40: [SM] Blaming: l4d2_jockey_skeet.smx
L 11/03/2019 - 20:45:40: [SM] Call stack trace:
L 11/03/2019 - 20:45:40: [SM]   [0] GetEdictClassname
L 11/03/2019 - 20:45:40: [SM]   [1] Line 141, plugin/EUplugins/march/l4d2_jockey_skeet.sp::IsShotgun
L 11/03/2019 - 20:45:40: [SM]   [2] Line 73, plugin/EUplugins/march/l4d2_jockey_skeet.sp::OnTakeDamage
L 11/03/2019 - 20:51:26: SourceMod error session started
L 11/03/2019 - 20:51:26: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 20:51:26: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 20:51:26: [UPDATER] Could not download "http://update.sourcemod.net/update/"
L 11/03/2019 - 20:51:26: [UPDATER] Error: Couldn't resolve host 'update.sourcemod.net'
L 11/03/2019 - 20:51:26: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 20:54:48: SourceMod error session started
L 11/03/2019 - 20:54:48: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 20:54:48: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 20:54:48: [UPDATER] Parse error in update manifest: Line contained too many invalid tokens
L 11/03/2019 - 20:54:48: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 22:04:20: Error log file session closed.
L 11/03/2019 - 22:11:32: SourceMod error session started
L 11/03/2019 - 22:11:32: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 22:11:32: [SM] Exception reported: Client index 385 is invalid
L 11/03/2019 - 22:11:32: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 22:11:32: [SM] Call stack trace:
L 11/03/2019 - 22:11:32: [SM]   [0] IsClientInGame
L 11/03/2019 - 22:11:32: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 22:11:32: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 22:14:18: [SM] Exception reported: Entity 5 (5) is invalid
L 11/03/2019 - 22:14:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 22:14:18: [SM] Call stack trace:
L 11/03/2019 - 22:14:18: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 22:14:18: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 22:14:18: [SM] Exception reported: Entity 2 (2) is invalid
L 11/03/2019 - 22:14:18: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 22:14:18: [SM] Call stack trace:
L 11/03/2019 - 22:14:18: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 22:14:18: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 22:14:19: Error log file session closed.
L 11/03/2019 - 22:15:54: SourceMod error session started
L 11/03/2019 - 22:15:54: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 22:15:54: [UPDATER] --- BEGIN ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 22:15:54: [UPDATER] Could not download "http://update.sourcemod.net/update/"
L 11/03/2019 - 22:15:54: [UPDATER] Error: Couldn't resolve host 'update.sourcemod.net'
L 11/03/2019 - 22:15:54: [UPDATER] --- END ERRORS FROM AUTOMATIC UPDATER ---
L 11/03/2019 - 22:18:38: SourceMod error session started
L 11/03/2019 - 22:18:38: Info (map "c2m1_highway") (file "errors_20191103.log")
L 11/03/2019 - 22:18:38: [CRASH] Accelerator uploaded crash dump: Crash ID: 7FXL-RYFO-ZI7N
L 11/03/2019 - 23:02:45: Error log file session closed.
L 11/03/2019 - 23:16:12: SourceMod error session started
L 11/03/2019 - 23:16:12: Info (map "c10m2_drainage") (file "errors_20191103.log")
L 11/03/2019 - 23:16:12: [SM] Exception reported: Client index 144 is invalid
L 11/03/2019 - 23:16:12: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:16:12: [SM] Call stack trace:
L 11/03/2019 - 23:16:12: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:16:12: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:16:12: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:16:19: [SM] Exception reported: Client index 144 is invalid
L 11/03/2019 - 23:16:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:16:19: [SM] Call stack trace:
L 11/03/2019 - 23:16:19: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:16:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:16:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:16:19: [SM] Exception reported: Client index 144 is invalid
L 11/03/2019 - 23:16:19: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:16:19: [SM] Call stack trace:
L 11/03/2019 - 23:16:19: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:16:19: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:16:19: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:16:21: [SM] Exception reported: Client index 144 is invalid
L 11/03/2019 - 23:16:21: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:16:21: [SM] Call stack trace:
L 11/03/2019 - 23:16:21: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:16:21: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:16:21: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:25:25: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/03/2019 - 23:25:25: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/03/2019 - 23:25:25: [SM] Call stack trace:
L 11/03/2019 - 23:25:25: [SM]   [0] SetEntProp
L 11/03/2019 - 23:25:25: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/03/2019 - 23:26:30: [SM] Exception reported: Entity 4 (4) is invalid
L 11/03/2019 - 23:26:30: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 23:26:30: [SM] Call stack trace:
L 11/03/2019 - 23:26:30: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 23:26:30: [SM]   [1] Line 115, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::Event_PlayerTeam
L 11/03/2019 - 23:26:33: Error log file session closed.
L 11/03/2019 - 23:27:53: SourceMod error session started
L 11/03/2019 - 23:27:53: Info (map "c10m3_ranchhouse") (file "errors_20191103.log")
L 11/03/2019 - 23:27:53: [SM] Exception reported: Client index 211 is invalid
L 11/03/2019 - 23:27:53: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:27:53: [SM] Call stack trace:
L 11/03/2019 - 23:27:53: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:27:53: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:27:53: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:27:53: [SM] Exception reported: Client index 211 is invalid
L 11/03/2019 - 23:27:53: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:27:53: [SM] Call stack trace:
L 11/03/2019 - 23:27:53: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:27:53: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:27:53: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:44:04: Error log file session closed.
L 11/03/2019 - 23:51:46: SourceMod error session started
L 11/03/2019 - 23:51:46: Info (map "c10m4_mainstreet") (file "errors_20191103.log")
L 11/03/2019 - 23:51:46: [SM] Exception reported: Entity -1 (-1) is invalid
L 11/03/2019 - 23:51:46: [SM] Blaming: l4d2_melee_shenanigans.smx
L 11/03/2019 - 23:51:46: [SM] Call stack trace:
L 11/03/2019 - 23:51:46: [SM]   [0] SetEntProp
L 11/03/2019 - 23:51:46: [SM]   [1] Line 142, crash/l4d2_melee_shenanigans.sp::TimedSwap
L 11/03/2019 - 23:52:09: [SM] Exception reported: Entity 4 (4) is invalid
L 11/03/2019 - 23:52:09: [SM] Blaming: l4d2_charger_getup_fix.smx
L 11/03/2019 - 23:52:09: [SM] Call stack trace:
L 11/03/2019 - 23:52:09: [SM]   [0] GetEntDataEnt2
L 11/03/2019 - 23:52:09: [SM]   [1] Line 89, C:\Users\Trevor_2\Desktop\scripting\l4d2_charger_getup_fix.sp::OnClientDisconnect
L 11/03/2019 - 23:52:11: Error log file session closed.
L 11/03/2019 - 23:58:54: SourceMod error session started
L 11/03/2019 - 23:58:54: Info (map "c10m5_houseboat") (file "errors_20191103.log")
L 11/03/2019 - 23:58:54: [SM] Exception reported: Client index 313 is invalid
L 11/03/2019 - 23:58:54: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:58:54: [SM] Call stack trace:
L 11/03/2019 - 23:58:54: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:58:54: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:58:54: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
L 11/03/2019 - 23:58:58: [SM] Exception reported: Client index 313 is invalid
L 11/03/2019 - 23:58:58: [SM] Blaming: l4d2_getup_slide_fix.smx
L 11/03/2019 - 23:58:58: [SM] Call stack trace:
L 11/03/2019 - 23:58:58: [SM]   [0] IsClientInGame
L 11/03/2019 - 23:58:58: [SM]   [1] Line 39, C:\Users\Sir\Documents\THE MAP\New Scripting\include\l4d2util_infected.inc::IsInfected
L 11/03/2019 - 23:58:58: [SM]   [2] Line 135, C:\Users\Sir\Documents\THE MAP\New Scripting\l4d2_getup_slide_fix.sp::L4D2_OnStagger
